### ISSUE TITLE
Readme pages sometimes missing scrollbar

### ISSUE THREAD

**Issue by theRealPadster** [spicetify/spicetify-marketplace#113]
**Describe the bug**
Sometimes when you click on a card and open the readme page, there is no scrollbar, when there should be. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Extensions
2. Click on Power Bar
3. Try scrolling

**Expected behaviour**
If entire page doesn't fit on the screen, it should always show the scroll bar and allow scrolling

**Desktop (please complete the following information):**
 - OS: Linux
 - Spicetify version: 2.8.4
 - Spotify version: Spotify version 1.1.72.439.gc253025e,
 - Marketplace version: 867ae2c8ab20a44edb672924aa86ff41508cd490

**Additional context**
I've seen it happen before to other extensions, and it doesn't seem consistent. Possibly a race condition for downloading the file, converting to html, and rendering the page?

**Comment by kyrie25** [comment]
Have been able to reproduce this on Readme pages where the majority of the content are images.
My hypothesis is that the length of the Readme is determined after the page is rendered but before images are loaded, therefore reports the incorrect length of the page.
![Spotify_1uXrHT0Lxf](https://user-images.githubusercontent.com/77577746/173046269-4f8736d6-bf32-4402-9dd2-5f3a207e468d.gif)

**Comment by theRealPadster** [comment]
Oh, yeah I think you're right. Since the images in the readme are generally relative links from the github repo, they don't load as absolute image `src` attributes. I've got some code running that fixes the URLs on error, so it's modifying the content after the page has been fully "loaded" already.

**Comment by theRealPadster** [comment]
It also fixes it if we put overflow-y: scroll on this `main`. Not sure how easy that is to target with css or something though...

<img width="932" alt="image" src="https://user-images.githubusercontent.com/1565883/173192919-608ccf30-6417-43e4-a5ec-cc463c53d1e1.png">

**Comment by kyrie25** [comment]
> It also fixes it if we put overflow-y: scroll on this `main`. Not sure how easy that is to target with css or something though...

Pretty easy I think, not sure if there is anymore tho, but I guess it shouldn't matter that much

![image](https://user-images.githubusercontent.com/77577746/173193142-d7b50047-2c60-4c81-b6bd-4a8f3ccfc3fd.png)

**Comment by theRealPadster** [comment]
I feel like that's not safe...

I added this to the ReadmePage, and it doesn't work. It adds the style, but no scrollbar shows up. If I remove and re-add it in the inpsector, then it works. Maybe a timing thing? 

<img width="671" alt="image" src="https://user-images.githubusercontent.com/1565883/173193298-0ce4b342-46e0-4920-a975-75e37fe9a7a7.png">

**Comment by kyrie25** [comment]
Try `!important` since that's the same problem I got with the Upgrade Snippet button.

**Comment by theRealPadster** [comment]
> Try `!important` since that's the same problem I got with the Upgrade Snippet button.

It's not that the rule doesn't apply. It's that it doesn't seem to take effect unless I set the rule via inspector.

**Comment by theRealPadster** [comment]
Yeah lol it's a timing thing. If I add a 1s `setTimeout`, then it works.
