### ISSUE TITLE
How to reset a theme manually

### ISSUE THREAD

**Issue by Zopenzop** [spicetify/spicetify-marketplace#132]
I installed a theme which is apparently broken, I can't access the marketplace page either. Can I reset the theme without having to reinstall spicetify marketplace?

**Comment by vluist** [comment]
1. in powershell do: spicetify enable-devtool
2. go to spotify and do ctrl+shift+i and go to the "console" tab (or right click anywhere in spotify and choose "show devtools")
3. paste Marketplace.reset()

this will reset all your spicetify marketplace settings (themes, snippets, extensions, etc.)
found this in discord, credits to Flafy

**Comment by CharlieS1103** [comment]
Going to be adding a section in the readme to make this feature easier to find.

**Comment by Myron2812** [comment]
> 1. in powershell do: spicetify enable-devtool
> 
>     2. go to spotify and do ctrl+shift+i (or right click anywhere in spotify and choose "show devtools") and go to the "console" tab
> 
>     3. paste Marketplace.reset()
> 
> 
> this will reset all your spicetify marketplace settings (themes, snippets, extensions, etc.) found this in discord, credits to Flafy

How do I do this on Linux?

![Screenshot from 2023-07-19 14-45-39](https://github.com/spicetify/spicetify-marketplace/assets/67193041/c0fda9cd-c2a0-4cb9-99d1-3db5d8d1c5fa)

I can't access anything
