### ISSUE TITLE
Spicetify Marketplace: Dynamic Dribblish Crash 

### ISSUE THREAD

**Issue by JayChen078** [spicetify/spicetify-marketplace#133]
Normal functioning marketplace that allowed me to do everything and I installed dynamic dribblish - then I turned on the option for a loading screen, which now, just crashes spotify every time I close and open it. The loading screen just sticks. 

I used, " spicetify config custom_apps spicetify-marketplace-main- " to remove the config info, and then deleted the actual spicetify marketplace main folder from the custom apps folder as well. 

Upon reinstallation of spicetify marketplace, using a brand new download from git-hub, "spicetify apply" launches right into the crashed loading screen again. 

Any fixes please?

**Comment by CharlieS1103** [comment]
@JayChen078 I recommend following the steps in the readme titled "Manual Reset" https://github.com/spicetify/spicetify-marketplace#manual-reset . Odds are this is a dribblish dynamic issue and not a marketplace issue, but if this doesn't work, please leave another comment.

**Comment by CharlieS1103** [comment]
@julienmaille

**Comment by JayChen078** [comment]
@CharlieS1103 

I fixed the issue - unsure what I did that fixed it, but it seemed like waiting a day and re-doing it worked. 

Manual reset in this case doesn't work, due to DribblishDynamic crashing  Spotify before access to marketplace can even occur for inspect element. I guess a question would be, even upon deleting the custom_app file of marketplace, reinstalling it, comes with all the previously installed marketplace apps, is there a way to reset default, before any apps in bash code?

**Comment by JulienMaille** [comment]
the marketplace crashes even *without* dribbblish, I'm also stuck without any solution to reset marketplace's settings.

**Comment by JayChen078** [comment]
@CharlieS1103 

Does a manual reset exist for marketplace in terminal? To return entirely to default, blank, no installs? Or is it only accessible thru inspect element commands?

**Comment by CharlieS1103** [comment]
Only accessible through inspect element commands? I find it odd that you're all experiencing crashes, mind sending your config file? ALso do other custom apps work for you?

**Comment by JayChen078** [comment]
**Manual Reset:

If you lose access to the marketplace page, and therefore cannot access the setting, follow these steps:

First ensure you have dev-tools enabled by running spicetify enable-devtool apply
Open up console by right clicking anywhere on Spotify (that isn't an element), and clicking inspect element.
Click the console tab in the devtools window that appears, and run the following command(in console)
Marketplace.reset()**

I was talking about this. I meant the dev-tools console. You cannot access the dev-tools if spotify crashes on startup.

**Comment by JayChen078** [comment]
![Screen Shot 2022-02-28 at 3 06 03 AM](https://user-images.githubusercontent.com/96325415/155947054-e7534a79-9335-40bc-b51a-01a1b40a3ec7.png)

Here's my config file.

**Comment by CharlieS1103** [comment]
@JayChen078 disable marketplace, open up devtools, hit the application tab, local storage, fund the xpui.js one, type "marketplace" in the filter bar and remove everything that starts with that tag.

**Comment by CharlieS1103** [comment]
The issue could be that you have dribblish.js running already, so I recommend using a. Theme that doesn't have js when using marketplace.
