### ISSUE TITLE
Use our own github topic

### ISSUE THREAD

**Issue by theRealPadster** [spicetify/spicetify-marketplace#137]
I suppose we have enough popularity now that we should probably add our own topic, like "spicetify-marketplace-theme" and "spicetify-marketplace-extension". That should cut down on all the 404s logged to the console from it picking up people just using the spicetify tags, when they don't have a `manifest.json`.

**Comment by CharlieS1103** [comment]
Should do it over time not immeaditey (make announcements about the transition and such)

**Comment by afonsojramos** [comment]
Any news when this will come into effect?

**Comment by theRealPadster** [comment]
> Any news when this will come into effect?

Nope. Nobody has made any effort on this.

**Comment by CharlieS1103** [comment]
Not really relevant anymore.
