### ISSUE TITLE
Add custom apps tab

### ISSUE THREAD

**Issue by theRealPadster** [spicetify/spicetify-marketplace#148]
### 📝 Provide a description of the new feature

It is not possible to inject custom apps via Marketplace, but it would still be helpful to provide a nice listing system for people to browse and share custom apps. 

We could make a custom apps tab and just have no install button, or make it link to the GitHub. Something so that items are still listed but you can't try and install them since it won't work anyways.

**Comment by CharlieS1103** [comment]
@theRealPadster Sounds good, one issue will just be filtering between extensions and custom apps.

**Comment by theRealPadster** [comment]
> @theRealPadster Sounds good, one issue will just be filtering between extensions and custom apps.

Yeah we'd need to add logic in to handle that. If there's no `main` and no `usercss` maybe. Or it might just be better to add a `type: string "extension" | "theme" | "app"` field at this point, to simplify things.

**Comment by theRealPadster** [comment]
Looks like there are two main tags people use (and there aren't a lot of custom apps on github anyways):
- [spicetify-apps](https://github.com/topics/spicetify-apps)
- [spicetify-custom-apps](https://github.com/topics/spicetify-custom-apps)

So we might want to scan both or just pick one. I vote "spicetify-apps"
