### ISSUE TITLE
Transferring extensions

### ISSUE THREAD

**Issue by maxlbgn** [spicetify/spicetify-marketplace#149]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version:1.1.81.604.gccacfc8c
- Spicetify version:2.9.2
```

### 📝 Description

Although the theme is successfully enabled, the album image cannot be displayed.

And error
Transferring extensions:
error Extension "fluent.js" not found.
error Extension "newRelease.js" not found.

I don't know if the two are related, sorry I'm a beginner, I just want to change the boring theme

### 📸 Screenshots

![截圖 2022-03-22 下午1 42 54](https://user-images.githubusercontent.com/70247471/159415701-a4154248-bdf2-4846-a5f4-15901905c349.png)
<img width="470" alt="截圖 2022-03-22 下午1 43 51" src="https://user-images.githubusercontent.com/70247471/159415773-a938ef62-6cdd-488d-a34a-6d397128da09.png">

**Comment by theRealPadster** [comment]
What is the error here? Sorry, I'm not familiar with the theme/extension you're using. Also, Marketplace has no access to local files, so any errors that Spicetify is throwing when applying is unrelated.

**Comment by CharlieS1103** [comment]
The issue is because you have those extensions defined in your config file but not installed locally
