### ISSUE TITLE
Fix theme installation color schemes updating

### ISSUE THREAD

**Issue by CharlieS1103** [spicetify/spicetify-marketplace#160]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 81
- Spicetify version: Latest
```

### 📝 Description

Patch theme installation
Currently, if you just go around installation random themes for a few seconds, you'll immediately find that color schemes eventually stop updating. (fixed after reloading the page.)

**Comment by theRealPadster** [comment]
Probably related to #110

**Comment by theRealPadster** [comment]
Is this still a thing?

**Comment by CharlieS1103** [comment]
@theRealPadster Believe it was resolved when we started using tsx
