### ISSUE TITLE
Add build action

### ISSUE THREAD

**Issue by theRealPadster** [spicetify/spicetify-marketplace#161]
### 📝 Provide a description of the new feature

I'm working on a build action so that GitHub will automate the build process. You can check out the actions branch to see it in action. Basically the idea is to have it run a build and commit that if there are changes. 

This will enable us to use spicetify-creator and have actual Typescript and JSX. And should make it so that you don't *have* to run a build if you're just changing something simple like an scss file. 

I'm not sure what rules we want to set up as far as when it runs. Likely just on the main branch, and we probably want to protect the main branch so it can only be committed to via PRs, if it's not already. 

I am also not sure what we want the auto-commit author and message to be. Currently it uses the previous commit author, but we could theoretically use something like "GitHub Actions". 

### ➕ Additional Information

- Actions branch: https://github.com/spicetify/spicetify-marketplace/commits/actions
- Spicetify-Creator: https://github.com/spicetify/spicetify-creator

**Comment by theRealPadster** [comment]
Added @CharlieS1103 @afonsojramos for discussion.

**Comment by theRealPadster** [comment]
Another possibility: store the source code in main and built version in a separate branch, like [here](https://github.com/jeroentvb/spicetify-power-bar/blob/master/.github/workflows/build.yml). Then we'd have our releases based on tags in that branch. 
![image](https://user-images.githubusercontent.com/1565883/162533223-c3c1f9b8-8e9d-4509-86c0-0eb32e667a55.png)

**Comment by afonsojramos** [comment]
Agree with that, but if you are already committing to the "dist" branch, you don't need a dist folder.

**Comment by theRealPadster** [comment]
> Agree with that, but if you are already committing to the "dist" branch, you don't need a dist folder.

Yeah we'd add to gitignore on the main branch

**Comment by afonsojramos** [comment]
No, I mean using something like this: https://github.com/marketplace/actions/push-git-subdirectory-as-branch

**Comment by theRealPadster** [comment]
> No, I mean using something like this: https://github.com/marketplace/actions/push-git-subdirectory-as-branch

Yes, that's what I meant. We'd have the build output in a branch and have no dist folder in the main branch. Like this: https://github.com/theRealPadster/spurdle/

**Comment by theRealPadster** [comment]
I thought about putting this into place, and then realized that we'd have to adjust the install scripts and anyone else that references us (like the easyinstaller probably) would need to update as well. Will see if I can get this set up on the actions branch.

**Comment by theRealPadster** [comment]
Upon further messing around with parcel, trying to get the styles built and then just copy the rest of the files to the dist folder, developing seems a little annoying. If you use the src folder, it won't have the built css, but if you use the dist folder, you won't have the updated files unless we have parcel build them or something. 

I have moved ahead with creating an "spcr" branch and started work porting Marketplace to Spicetify Creator instead. It's going fairly well. Will make development and maintenance a lot nicer. The build process is also a lot easier to manage.

**Comment by theRealPadster** [comment]
I've added the build action I'm using for my Name That Tune app, which is also made with Spicetify Creator and it works. 
I've got it running on the spcr branch (which will be merged into main at some point), pushing to a [dist](https://github.com/spicetify/spicetify-marketplace/tree/dist) branch. We can tweak the behaviour later, but I believe this resolves this issue.
