### ISSUE TITLE
Broken marketplace view

### ISSUE THREAD

**Issue by tonytkachenko** [spicetify/spicetify-marketplace#170]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for Windows 1.1.83.956.gbe7ea9a7
- Spicetify version: 2.9.6
```

### 📝 Description

The marketplace is broken after updating spicetify to 2.9.6
Reinstalled both of them, removed all configs but always get this view:

### 📸 Screenshots

![Image 007](https://user-images.githubusercontent.com/103267335/164866091-49662543-1624-4732-a59b-63ce521eca0a.png)
![Image 008](https://user-images.githubusercontent.com/103267335/164866092-1d83ad51-a914-4f48-ae96-b6a8499174f0.png)
![Image 009](https://user-images.githubusercontent.com/103267335/164866093-160b5a68-31ed-4300-bde6-a798c65504bc.png)

**Comment by sph3** [comment]
When I install the marketplace, it breaks spotify entirely.

**Comment by CharlieS1103** [comment]
Ypdate marketplace
