### ISSUE TITLE
Installing marketplace breaking everything

### ISSUE THREAD

**Issue by sph3** [spicetify/spicetify-marketplace#173]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.72.439.gc253025e
- Spicetify version: 2.9.6
```

### 📝 Description

Installing only Spicetify works, but then after installing the marketplace, it breaks.

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/59633047/164991025-c66e24f6-930a-432d-be1f-4ce41f0fb444.png)

**Comment by Guiki18** [comment]
![image](https://user-images.githubusercontent.com/72317733/165739484-aa04c5bd-0470-4e7e-ba53-7dc9385313dd.png)
Same problem here, that's happend when i add `spicetify-marketplace` to `custom_apps`, when i remove and apply, that's solve the problem, i was looking up for the issue

**Comment by theRealPadster** [comment]
Any update on this, with newer spicetify versions?

**Comment by Guiki18** [comment]
it took me awhile and at the check, I stopped using Windows, let me re-install the updated spicetify and try again

**Comment by Guiki18** [comment]
On linux they are working perfectly, i was testing in Windows now

**Comment by Guiki18** [comment]
On windows to
![image](https://user-images.githubusercontent.com/72317733/170828271-d4e909dd-67e7-442b-aaed-9af19bbafa96.png)

**Comment by Guiki18** [comment]
Linux:
![image](https://user-images.githubusercontent.com/72317733/170828405-7317a38a-d035-474b-9297-262861aefba1.png)


I think i solved the problem on both windows and linux updating spotify to version 1.80. ...

**Comment by CharlieS1103** [comment]
Patched
