### ISSUE TITLE
Marketplace showing only a little number of customizations

### ISSUE THREAD

**Issue by brunosaragiotto** [spicetify/spicetify-marketplace#184]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.84.716.gc5f8b819
- Spicetify version: 2.9.8
```

### 📝 Description

Today I reinstall the spotify, and after that I install the spicetify and the marketplace. After that, open the marketplace tab, and open I only see one extension and seven themes. I search for reported issues, but not found on here, but i found in spicetify closed issues. 

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/10796621/167668076-7e74bf41-c0c5-483c-a5e0-8d360f1bce09.png)
![image](https://user-images.githubusercontent.com/10796621/167668109-5abe29d7-9818-4dc7-9328-8d0bda2306b2.png)
![image](https://user-images.githubusercontent.com/10796621/167668145-e2ecd84a-41cd-4542-af9e-979803d05937.png)

**Comment by ulisesvina** [comment]
Same issue is replicable on macOS Monterey, latest Spotify and spicetify versions.

**Comment by LuckyTarget** [comment]
Same..

**Comment by CharlieS1103** [comment]
Solved.
