### ISSUE TITLE
Opening Marcetplace shows error

### ISSUE THREAD

**Issue by SpeeterYT** [spicetify/spicetify-marketplace#194]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version:Spotify für Windows
1.1.85.895.g2a71e1b8
- Spicetify version: 2.10.0
```

### 📝 Description

Opening the Marcetplace just shows error

### 📸 Screenshots

https://i.imgur.com/8pgBz9q.png

**Comment by Dunkran** [comment]
I have the same issue, I just reinstalled everything and nothing changed.

**Comment by phyzaz** [comment]
same here, but im on 
Spotify for Windows
1.1.86.857.g3751ee08

**Comment by DEWOREEK** [comment]
Same On 
1.1.84.716.gc5f8b819-8

**Comment by brenden7158** [comment]
I am also getting the same error
Spotify for Windows
1.1.84.716.gc5f8b819

**Comment by MyndPhreak** [comment]
Same as well
Spotify for Windows
1.1.86.857.g3751ee08

**Comment by NanaAY** [comment]
dont think market place works with spicetify 2.10 and above

**Comment by theRealPadster** [comment]
The problem is certain Spicetify hooks being broken on Spotify 1.1.85/1.1.86 and Spicetify 2.9.x/2.10.0. Did you try 2.10.1?

**Comment by owen-the-kid** [comment]
same on ubuntu

**Comment by CharlieS1103** [comment]
Patched as of Spicetify V2.10.1

**Comment by phyzaz** [comment]
still doesnt work on 
Spotify for Windows
1.1.86.857.g3751ee08
 and 2.10.1

**Comment by Miusaky** [comment]
Still broken for me on 2.10.1; Spotify version 1.1.84_1.

**Comment by theRealPadster** [comment]
> Still broken for me on 2.10.1; Spotify version 1.1.84_1.

I don't think those versions are meant to work together. 2.10.1 is for Spotify 1.1.85 or 1.1.86

**Comment by prateekamana** [comment]
> im on 1.1.85 with spicetify 2.10.1 and it works s you might have to downgrade your Spotify

@NanaAY How did you downgrade it? I can't find the .deb's for previous versions
