### ISSUE TITLE
Upgrade button showing every time Spotify starts although the snippet to hide it is installed

### ISSUE THREAD

**Issue by pafase** [spicetify/spicetify-marketplace#196]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for Windows 1.1.86.857.g3751ee08
- Spicetify version: 2.10.1
- Windows 10 21H2
```

### 📝 Description

Every time Spotify starts, I have to reinstall the Hide Upgrade Button Snippet to get it working. This problem is not new to this version, as this has been a problem since late April (it was Spotify 1.184.716 and Spicetify 2.9.8 iirc).

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/51797598/170834761-5b4b571a-0411-4568-ae81-e850cc5d2f6e.png)

**Comment by theRealPadster** [comment]
@CharlieS1103 the auto-hide friends snippet was broken, so this is probably as well. Would you be able to take a look? I don't have it on my Spotify.

**Comment by kyrie25** [comment]
Not reproducible
![Spotify_DrmqUH2tk1](https://user-images.githubusercontent.com/77577746/173034778-2db26475-111a-460a-8f26-af5259089792.gif)
