### ISSUE TITLE
Make sure the logic with requestPage is correct 

### ISSUE THREAD

**Issue by CharlieS1103** [spicetify/spicetify-marketplace#198]
### 📝 Provide a description of the new feature

(needs to be a number, original logic has it sometimes null)

**Comment by theRealPadster** [comment]
Hey @kyrie25 , you probably understand this stuff more than I do, since you did the search thing. Does it look good to you?

**Comment by kyrie25** [comment]
> Hey @kyrie25 , you probably understand this stuff more than I do, since you did the search thing. Does it look good to you?

LGTM. I don't see any references where requestPage is reassigned to null but if that were the case, there are already functions in the script to reassign the variable to a number
