### ISSUE TITLE
Get the settings modal working

### ISSUE THREAD

**Issue by CharlieS1103** [spicetify/spicetify-marketplace#199]
### 📝 Provide a description of the new feature

It looks like it's applying but I need to update state on the App, and the modal isn't updating...
  - Using the `app.triggerRefresh` makes it apply in real time in the background (e.g. when toggling stars)
  - Using a `forceUpdate` in the `SettingsToggle` can make the toggle update
  - It's probably because the modal isn't in the app's component tree, so state changes don't affect it!

**Comment by theRealPadster** [comment]
Update: 
- Visual settings work
- Tab show/hide works
- Tab reordering doesn't work
- Tab toggles don't use same component as visual setting toggles. Need to finish refactoring. 
- It also doesn't reload on modal close
