### ISSUE TITLE
Add sortbox styling

### ISSUE THREAD

**Issue by CharlieS1103** [spicetify/spicetify-marketplace#200]
### 📝 Provide a description of the new feature

Looks rather poor currently.

**Comment by theRealPadster** [comment]
This is 90% done. Need to figure out how to make the width always equal to the length of the longest option. 

<img width="268" alt="image" src="https://user-images.githubusercontent.com/1565883/170848309-7c152df6-c0be-4cc2-908d-c94e7782629f.png">

**Comment by theRealPadster** [comment]
Tab bar version still needs to be styled.

**Comment by theRealPadster** [comment]
Done in c41a3a5608cd86852fe28eeeaeff880ac1c1b1ee
