### ISSUE TITLE
Add a working dropdown to `TabBarMore`

### ISSUE THREAD

**Issue by theRealPadster** [spicetify/spicetify-marketplace#202]
### 📝 Provide a description of the new feature

Add a working dropdown to `TabBarMore`, like how it used `OptionsMenu` before. 

### ➕ Additional Information

This is for the tab bar when your window is too narrow to show all the tabs. 
<img width="672" alt="image" src="https://user-images.githubusercontent.com/1565883/170843239-b35ddcc3-9eb0-4a73-8fb9-af2000c9eea8.png">

**Comment by theRealPadster** [comment]
This is working now, using the react-dropdown library. It just needs to be styled to fit in with the tab bar
<img width="440" alt="image" src="https://user-images.githubusercontent.com/1565883/170848280-5e1cc42a-464b-45bb-9f6e-febb686fc0f4.png">

**Comment by FlafyDev** [comment]
You can use [spcr-navigation-bar](https://github.com/FlafyDev/spicetify-creator-plugins/tree/main/packages/spcr-navigation-bar) or look at the code (haven't tested it in a while)

**Comment by theRealPadster** [comment]
> You can use [spcr-navigation-bar](https://github.com/FlafyDev/spicetify-creator-plugins/tree/main/packages/spcr-navigation-bar) or look at the code (haven't tested it in a while)

Does it use the spicetify methods to create the drop-down? I had planned on using it, but we're using a separate library because the spicetify drop-down hook or code has been quite broken for quite a while.

**Comment by theRealPadster** [comment]
Done in c41a3a5608cd86852fe28eeeaeff880ac1c1b1ee
