### ISSUE TITLE
Something went wrong error

### ISSUE THREAD

**Issue by phyzaz** [spicetify/spicetify-marketplace#205]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version:
Spotify for Windows
1.1.86.857.g3751ee08
- Spicetify version: 2.10.1 (latest currently)
```

### 📝 Description

I get this error when trying to open the marketplace. i have tried to reset it using the devtools console.  Even after refreshing the page using the nice button - it doesnt work.

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/106193324/170886546-33ba56de-40be-491b-855c-3ff880f958b6.png)

**Comment by Gamershy** [comment]
I ahve the same error, seems something's wrong in the latest update.

**Comment by karimawii** [comment]
same

**Comment by CharlieS1103** [comment]
not a marketplace issue

**Comment by Gamershy** [comment]
How is it not a marketplace issue?

**Comment by phyzaz** [comment]
> not a marketplace issue

what could the issue stem from then, it seems pretty related with marketplace...

**Comment by theRealPadster** [comment]
> what could the issue stem from then, it seems pretty related with marketplace...

The Spicetify hooks being broken.
