### ISSUE TITLE
Display Snippet content upon clicking on Snippet cards

### ISSUE THREAD

**Issue by kyrie25** [spicetify/spicetify-marketplace#221]
### 📝 Provide a description of the new feature

Display Snippets’ CSS content upon clicking on its cards instead of showing a toast notification saying “No page is found”.
**Note**: This can be used for `Add CSS` button also to allow code editing with IntelliSense right inside Marketplace ~~which is pretty cool~~.

Or alternatively disable the toast notification in the Snippets tab since it does not contain any useful information.

### ➕ Additional Information

Current state:
![6A7A6B7F-5C46-4455-8E58-7CDCFBE6539E](https://user-images.githubusercontent.com/77577746/172682697-13902ea0-922c-4397-b1f5-2bf2c86ab8d5.png)

Some proposed code editors:
- [Monaco Editor](https://microsoft.github.io/monaco-editor/index.html) (basically VS Code editor) and its React library [@monaco-editor/react](https://www.npmjs.com/package/@monaco-editor/react#usemonaco)
- [React Simple Code Editor](https://www.npmjs.com/package/react-simple-code-editor)
- [React Ace](https://www.npmjs.com/package/react-ace)

**Comment by theRealPadster** [comment]
Is this resolved with the href you added? Or should we display a non-editable version of the "add CSS" modal?

I do like the idea of having an actual editor for the CSS input.

**Comment by kyrie25** [comment]
> Is this resolved with the href you added?

Sadly no, my PR earlier only redirects users to the `snippets.json` file where it is stored.

> Or should we display a non-editable version of the "add CSS" modal?
I do like the idea of having an actual editor for the CSS input.

Indeed, yes.
I was thinking of having the editor contained inside the `Custom CSS` text area (definitely need to make the popup bigger in order to fit in the editor)
![image](https://user-images.githubusercontent.com/77577746/172764197-57b52188-5fc5-40d8-8bc3-65feebd8d7f5.png)

**Comment by kyrie25** [comment]
Tbh I think either displaying just the CSS content or removing the toast notification is fine if implementing a editor is too much of a hassle.

**Comment by kyrie25** [comment]
@theRealPadster I have successfully implemented the feature so far and can make a PR if you're satisfied with just displaying the CSS content, the editor can wait.
![image](https://user-images.githubusercontent.com/77577746/172775663-5051d969-f496-46ec-ba8a-833dc8a89592.png)

**Comment by CharlieS1103** [comment]
@kyrie25 ADditional feature, would it be possible to make it so that if its a custom CSS snippet (user added) it is editable??

**Comment by kyrie25** [comment]
> @kyrie25 ADditional feature, would it be possible to make it so that if its a custom CSS snippet (user added) it is editable??

As of now, there is no way to differentiate between an user-added snippet and a premade one since they are treated the same. I'll probably have to tinker around with `localStorage` to add another field that says so.
