### ISSUE TITLE
Add Preview images for Snippets

### ISSUE THREAD

**Issue by kyrie25** [spicetify/spicetify-marketplace#222]
### 📝 Provide a description of the new feature

Add Preview images similar to Extensions/Themes for Snippets in addition to the description.

**Comment by theRealPadster** [comment]
- I've started work on this. I'll need preview images for all our default snippets. 
- Also need to decide what to do if there is no image for a snippet. 
- And we could potentially allow the user to upload an image for their own custom snippets, either via a URL or by storing the image as base64 in the localstorage data. Not sure if worth it though.

**Comment by kyrie25** [comment]
For the non-images one, I'm sure a placeholder like the Spicetify logo would do.
As for the base64 encoded images, I'd prefer using a GitHub Raw URL to fetch the images as it'd be easier to update and maintain without changing too much data on the user's side. But if there is no need to update them then base64 would do.

**Comment by theRealPadster** [comment]
> As for the base64 encoded images, I'd prefer using a GitHub Raw URL to fetch the images as it'd be easier to update and maintain without changing too much data on the user's side. But if there is no need to update them then base64 would do.

I just meant for user-added snippets, we could use an HTML file upload input and store the image as base64 so they don't need to go and host their image somewhere and then paste the URL in.

**Comment by kyrie25** [comment]
Oh I see, that would be the optimal solution I agree. Need to add a base64 converter into util also.
