### ISSUE TITLE
Not loading/something went wrong etc. 

### ISSUE THREAD

**Issue by theRealPadster** [spicetify/spicetify-marketplace#223]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.86g3751ee08
- Spicetify version: 2.10.1
```

### 📝 Description

A lot of people still seem to be having issues with 2.10.1 and 1.1.86. Just making an issue to track here. 

From FreverZ on Discord. 

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/1565883/172719143-d9d370bd-e20a-43c3-8448-28e7091c86b4.png)

**Comment by CharlieS1103** [comment]
@theRealPadster This isn't a marketplace error though right?

**Comment by theRealPadster** [comment]
I guess probably not, but still want to figure out what's going on

**Comment by Volern** [comment]
Also having this issue. From what I've found when you try to install the marketplace through powershell when it installs marketplace it says "error Custom app "spicetify-marketplace" does not have index.js".

I presume this is the reason its not working but I have no prior experience with how spicetify works.

**Comment by theRealPadster** [comment]
it says "error Custom app "spicetify-marketplace" does not have index.js".

You should not have a folder or custom app called spicetify-marketplace. It's just called marketplace now.

**Comment by BlueDev5** [comment]
I'm having the same issue, I did find someone saying that downgrade to 2.9.9 spicetify worked, but for me I downgraded and upgraded and now its at least being able to apply themes, but now If I add marketplace to custom apps then spotify just show something went wrong and keeps asking for reloading the page, also as I wasn't able to get the dev tools to open up, I can't say what the problem could be (I'm using the apt version of spotify 1.1.84)

**Comment by theRealPadster** [comment]
@BlueDev5 Yeah, if you're stuck on Spotify 1.1.84, then just use Spicetify 2.9.9.

**Comment by CharlieS1103** [comment]
turns out there's a chance this is our bad, idk what the createPortal error is but it seems to be caused by us lol @theRealPadster

**Comment by AestheticalZ** [comment]
Having this issue with spicetify 2.10.2, on Spotify for Windows
1.1.89.862.g94554d24, but it just stays blank and the dev console spews out some errors.
![image](https://user-images.githubusercontent.com/51166756/178158184-b49faa5a-eedc-44b5-a5a4-168595f80ab6.png)

**Comment by MCFDev** [comment]
![image](https://user-images.githubusercontent.com/84239821/178158998-b02d3183-d940-4ef3-b7a6-bf11ef801216.png)
having this same issue on Linux (ParrotOS Security)  | Spicetify 2.10.2 | Spotify 1.1.84.716.gc5f8b819

**Comment by theRealPadster** [comment]
> ![image](https://user-images.githubusercontent.com/84239821/178158998-b02d3183-d940-4ef3-b7a6-bf11ef801216.png) having this same issue on Linux (ParrotOS Security) | Spicetify 2.10.2 | Spotify 1.1.84.716.gc5f8b819

Use spicetify 2.9.9 on Linux for now because it's stuck on Spotify 1.1.84

**Comment by theRealPadster** [comment]
> How do I downgrade _**Spicetify**_ through powershell (not spotify)
I'm not sure; I don't use Spicetify on Windows. Ask on Discord or the spicetify-cli repo.

**Comment by wyldcrd** [comment]
> > How do I downgrade _**Spicetify**_ through powershell (not spotify)
> 
> I'm not sure; I don't use Spicetify on Windows. Ask on Discord or the spicetify-cli repo.

I will go bother them then.

**Comment by kyrie25** [comment]
> Having this issue with spicetify 2.10.2, on Spotify for Windows 1.1.89.862.g94554d24, but it just stays blank and the dev console spews out some errors. ![image](https://user-images.githubusercontent.com/51166756/178158184-b49faa5a-eedc-44b5-a5a4-168595f80ab6.png)

@AestheticalZ Outdated Marketplace, not related to the issue mentioned.

**Comment by meteorsquare** [comment]
On Windows 11, mine don't load after updating Spicetify (I was on 2.9.0). Might be because of my outdated Spotify version (1.1.78).

**Comment by wyldcrd** [comment]
> On Windows 11, mine says "Something went wrong" after updating Spicetify (I was on 2.9.0 I think?). Might be because of my outdated Spotify version (1.1.78). I updated the Marketplace as well to the latest (v0.7.0). I don't wanna update Spotify yet. I updated the Marketplace as well.
> 
> I went down to Spicetify 2.9.8. Marketplace is working again.

How exactly did you downgrade spicetify? I can't figure it out @meteorsquare .
(Spotify also auto-updated and in my infinite stupidity forgot to make a backup beforehand, reinstalling everything gives me this issue.)

**Comment by meteorsquare** [comment]
Not sure how exactly but when I upgraded Spicetify to the latest version, the folder with the config file and custom app folders, etc. (it was on `Users\username\.spicetify`) migrated to another location (in `Users\username\AppData\Roaming\spicetify`). 

I think I manually installed an earlier version by replacing the files ones on the `user\Local\Roaming\spicetify` folder. I tried it on the Documents folder but didn't work.

Apologies for not being able to answer clearly. I was also struggling to downgrade.

**Comment by wyldcrd** [comment]
@theRealPadster will this be fixed/patched in the next version of spicetify/spicetify marketplace?

**Comment by theRealPadster** [comment]
> @theRealPadster will this be fixed/patched in the next version of spicetify/spicetify marketplace?

No, this is a generic issue and every version of spicetify/spotify is different and has slightly different problems. It seems to work fine on the latest version of both at the moment (1.1.90 and 2.11.1)

**Comment by CharlieS1103** [comment]
@theRealPadster We could try to replace the react.createPortal thing lol

**Comment by wyldcrd** [comment]
> > @theRealPadster will this be fixed/patched in the next version of spicetify/spicetify marketplace?
> 
> No, this is a generic issue and every version of spicetify/spotify is different and has slightly different problems. It seems to work fine on the latest version of both at the moment (1.1.90 and 2.11.1)

i get this problem when i install it on the latest version
HOW DO I FIX IT THEN

**Comment by theRealPadster** [comment]
> i get this problem when i install it on the latest version
HOW DO I FIX IT THEN

As I said before, it depends what is actually causing the issue, since that message that comes up doesn't point to anything in particular, just that something isn't working. 

I am not having any issues when I use it. I do not know what the issue is on your system. I can not fix it if I don't know what the problem is. 

 I also don't have a lot of time and quite frankly am getting annoyed at people complaining and complaining about things not working and acting entitled about a project that takes time and effort when people have actual lives with other things to do. I am not going to be responding on this issue anymore. I will leave it open so people don't go and make a new one every few days, but I am done discussing this.

**Comment by CharlieS1103** [comment]
@Volern @AestheticalZ @meteorsquare @wyldcrd Simply rerun the marketplace install script and it should now work.
