### ISSUE TITLE
Marketplace won't load

### ISSUE THREAD

**Issue by Surferlul** [spicetify/spicetify-marketplace#227]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.84.716.gc5f8b819
- Spicetify version: 2.10.1
```

### 📝 Description

Marketplace won't load even though I called Marketplace.reset()

## Setup:
- Fedora 36
- Spotify from dl.flatpak.org

## Possible Differences:
- spotify in ~/.var/app/com.spotify.Client/
- offline.bnk in ~/.var/app/com.spotify.Client/cache/spotify
- -> linked ~/.var/app/com.spotify.Client/cache/spotify to ~/.cache/spotify so that spicetify could enable devtools

### 📸 Screenshots

Screenshot after
1. Calling Marketplace.reset()
2. Pressing the Reaload Page button
![image](https://user-images.githubusercontent.com/66851546/172957653-73b0f75c-e1d7-4d14-b437-1334a960bdd3.png)

**Comment by theRealPadster** [comment]
I don't think spicetify 2.10.1 works with Spotify 1.1.84. could you try with 2.9.9 or something?

**Comment by Surferlul** [comment]
Did a complete reinstall of spicetify (-> 2.9.9) and spotify (manuallly deleting configs in ~/.var). Works now
