### ISSUE TITLE
Custom CSS snippets not showing in Installed tab

### ISSUE THREAD

**Issue by Franz321** [spicetify/spicetify-marketplace#233]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.85.895.g2a71e1b8
- Spicetify version: 2.10.1

Windows 10
```

### 📝 Description

Snippets added via the "+Add CSS" button are working but are not listed in the Installed tab, making it not possible to view your snippets and/ or uninstall them.

**Comment by theRealPadster** [comment]
Can you open the devtools, go to this page, and make this search? 
<img width="1152" alt="image" src="https://user-images.githubusercontent.com/1565883/173192477-09a9dc1c-a0fd-4422-a501-ff23417a538f.png">

**Comment by Franz321** [comment]
No, I already deleated the CSS snippet there, but the name of it was in the list in "marketplace:installed-snippets" and there was a key named after it, that I deleted

**Comment by theRealPadster** [comment]
Was there a space in the name? I noticed a bug like this when I was adding the snippet previews, but I pushed up a fix with that.

**Comment by Franz321** [comment]
Sorry, I really dont know that anymore.

**Comment by theRealPadster** [comment]
I'm guessing that's what the problem was. Closing as solved.
