### ISSUE TITLE
Marketplace not working correctly

### ISSUE THREAD

**Issue by R2-iDiot2** [spicetify/spicetify-marketplace#238]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for Windows
1.1.87.612.gf8d110e2
- Spicetify version: 2.10.1
```

### 📝 Description

So when I click on marketplace this happens (screenshot 1), upon clicking any of the 3 tabs or on the load more button, the button simply disappears (screenshot 2). Same issue for the themes tab except the button doesn't appear at all(screenshot 3). Same for snippets tab(screenshot 4). When the friends panel is open and more is displayed, upon clicking on more, only a black bar (I guess embed) appears with no text in it. Only the installed button works(screenshot 5).

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/96367432/174060357-eb6ced06-f258-46bb-b418-e614aa8af7c4.png)
![image](https://user-images.githubusercontent.com/96367432/174060382-a8d295b4-db4e-48a6-b8dc-5af1b812a9ab.png)
![image](https://user-images.githubusercontent.com/96367432/174060400-af9bd118-2de9-49cd-9459-0c6ba7d33aff.png)
![image](https://user-images.githubusercontent.com/96367432/174060425-e4897000-7e7f-4857-9599-7fc9db6ccbc9.png)
![image](https://user-images.githubusercontent.com/96367432/174060453-2062cc46-66d7-4e6f-b4fa-ac62af269763.png)

**Comment by kyrie25** [comment]
Outdated Marketplace, update and try again.
