### ISSUE TITLE
Fix progress bar displacement snippet preview image is tiny

### ISSUE THREAD

**Issue by theRealPadster** [spicetify/spicetify-marketplace#254]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.86
- Spicetify version: 2.10.1
```

### 📝 Description

Fix progress bar displacement snippet preview image is tiny. Could we make it a bit bigger? Cropping the blank space around should help, just keep it centred inside a square. 

### 📸 Screenshots

<img width="254" alt="image" src="https://user-images.githubusercontent.com/1565883/175354592-01b4bc20-929c-400a-a23f-a20c3170aeb1.png">

**Comment by kyrie25** [comment]
Not a bug, the image was submitted by the user which happens to be unexpectedly tiny lol #253
![image](https://user-images.githubusercontent.com/77577746/175427974-a3438813-2916-41f7-af1c-c11bf02ea9d2.png)

**Comment by theRealPadster** [comment]
I know. Just wanted to make an issue so we remember to crop it
