### ISSUE TITLE
Create backup option for installed items

### ISSUE THREAD

**Issue by CharlieS1103** [spicetify/spicetify-marketplace#290]
### 📝 Provide a description of the new feature

We can simply allow them to copy a Json  and then allow them to paste in said json into an input field and set that as their installed extensions and themes

**Comment by kyrie25** [comment]
Would there even be a significant benefit in doing so? Marketplace configuration is never lost unless the user reinstall Spotify itself, which is very unlikely. And therein lies the possibility of an invalid input, item does not exist in Marketplace for reinstallation upon apply, changes that has happened in the repository that the backup has not been up-to-date yet (eg. URL, repo, username changes), etc.

**Comment by CharlieS1103** [comment]
i would say it's worth it tbh, particularly with the addition of custom snippets.

**Comment by kyrie25** [comment]
I'd beg the differ, snippet codes are now viewable anw and there's no actual use case for extensions, and particularly themes when you can only install one at a time. But suit yourself ig.

**Comment by kyrie25** [comment]
But from what I see it will bring more trouble that benefits.

**Comment by theRealPadster** [comment]
This would be helpful for users with more than one device as well.

**Comment by theRealPadster** [comment]
I started a branch. Export would just export the any localstorage keys starting with "marketplace:". Import would just dump the localstorage keys back into localstorage. Custom snippet images can break it though since they can be huge. It froze my Spotify when I tried to put that into the text box.

**Comment by CharlieS1103** [comment]
@theRealPadster I think as far as merging that branch goes, just needs some polishing and we should be all set?

**Comment by glisteningcoder** [comment]
I know that I am late to the conversation but I think this idea would be great. I have been using Marketplace for quite a while now and I found it frustrating to just redownload every single item I have installed after using BleachBit to reclaim space. (I haven't investigated into this issue yet btw)

**Comment by CharlieS1103** [comment]
@glisteningcoder That'd be because bleach it clears application caches and that's where marketplace stores most of its data.

**Comment by glisteningcoder** [comment]
> @glisteningcoder That'd be because bleach it clears application caches and that's where marketplace stores most of its data.

Oh really? I will remember to leave it out next time I run then. Anyway it'd be nice if there are backups for this sort of thing.
