### ISSUE TITLE
Characters encoding error on installation

### ISSUE THREAD

**Issue by Twiz0x** [spicetify/spicetify-marketplace#291]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 2.11.1
- Spicetify version: 2.11.1
```

### 📝 Description

Trying to install spictify marketplace with "ë" caracter in username name is not working, see the error in the screen below.

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/78769585/181933853-68f4bc59-7549-4c0f-b903-2e8d366199dd.png)

**Comment by CharlieS1103** [comment]
mind pasting in the full error in plain text

**Comment by CharlieS1103** [comment]
Nevermind, this is a permission denied error and not related to marketplace most likely. You should try running as administrator, or ask for support in the discord.

**Comment by Twiz0x** [comment]
Nope, the error is because spicetify marketplace think the user is Rapha|-l and not Raphaël, so he doesn't have the permission because the user doesn't exist. You should check how to support characters like "ë"

**Comment by kyrie25** [comment]
This error occurs on installation script, **not** a Marketplace error.
