### ISSUE TITLE
Add possibility to translate

### ISSUE THREAD

**Issue by xerta555** [spicetify/spicetify-marketplace#302]
### 📝 Provide a description of the new feature

Hi

It could be possible to add translation(s) to this project ?
I have tried to edit the `index.js` file, but apparently it simply breaks the loading function of the requested web page.

Bref, i think hat it could be interesting to do that as this custom app have a settings page too.

Have a good day.

**Comment by CharlieS1103** [comment]
I mean, in terms of translating all the marketplace text it wouldn't be so hard, but using an external api to translate all the extensions themes and custom apps as they're loaded in, while easy to implement, would be immediately rate limited and cause the loading speed to go down drastically.

**Comment by xerta555** [comment]
> I mean, in terms of translating all the marketplace text it wouldn't be so hard, but using an external api to translate all the extensions themes and custom apps as they're loaded in, while easy to implement, would be immediately rate limited and cause the loading speed to go down drastically.

I didn't speacking about translating all themes, tools, script's descriptions etc, but just about the main and setting's menu.

Indeed, translating all the modules, themes, scripts as you go along would be just a hell of a thing to manage, but the basic elements of the Marketplace, it would already be good and even essential.

If module creators want to offer translations that they can provide on each of their repo, why not, but for me it should be the result of their efforts and not yours.

**Comment by theRealPadster** [comment]
This is a decent idea actually. I'm just not sure how we'd manage the translations.

**Comment by CharlieS1103** [comment]
@theRealPadster in terms of translating the marketplace text it'd be as simple as substituting all the text lines with variables and setting those variables according to the users settings(and storing and setting all the variables  in translations.ts or something). If we wanted to translate the themes and extensions it would be hellish.

**Comment by theRealPadster** [comment]
> @theRealPadster in terms of translating the marketplace text it'd be as simple as substituting all the text lines with variables and setting those variables according to the users settings(and storing and setting all the variables in translations.ts or something). If we wanted to translate the themes and extensions it would be hellish.

Yeah, I meant where and what format they'd be stored in, how you'd access them, etc.

**Comment by CharlieS1103** [comment]
> > @theRealPadster in terms of translating the marketplace text it'd be as simple as substituting all the text lines with variables and setting those variables according to the users settings(and storing and setting all the variables in translations.ts or something). If we wanted to translate the themes and extensions it would be hellish.
> 
> 
> 
> Yeah, I meant where and what format they'd be stored in, how you'd access them, etc. 

Wouldn't we be able to just store them as javascript objects and then create getter functions?

**Comment by theRealPadster** [comment]
> Wouldn't we be able to just store them as javascript objects and then create getter functions?

I'm wondering what libraries the are, so we could have a good standardized structure so people could make PRs with new languages. Quick search found this, but I haven't really looked into anything else. 
https://www.npmjs.com/package/simply-translate

**Comment by theRealPadster** [comment]
Got some good progress in. It can auto-detect your language from Spotify as well. So I don't think we even need a config setting for it. 

![image](https://user-images.githubusercontent.com/1565883/187574536-f9907afc-79c8-45e7-8ba7-ca03011a59ca.png)

**Comment by theRealPadster** [comment]
Made a new branch and draft PR with my work so far. #307

**Comment by xerta555** [comment]
French one added in pr: https://github.com/spicetify/spicetify-marketplace/pull/308

**Comment by theRealPadster** [comment]
@xerta555 I've added some more strings. Would you be able to add their French versions? The untranslated ones are wrapped in ().

**Comment by xerta555** [comment]
> @xerta555 I've added some more strings. Would you be able to add their French versions? The untranslated ones are wrapped in ().

My update is here: https://github.com/xerta555/spicetify-marketplace/commit/73fcb0a9bbb94a1f87a915380f66d2a8d4b79fee but i can't merge it in a pr on the main repo, don't know why
