### ISSUE TITLE
"Fix playlist arrows" snippet doesn't work

### ISSUE THREAD

**Issue by theRealPadster** [spicetify/spicetify-marketplace#315]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for macOS (Apple Silicon)
1.1.93.896.g3ae3b4f3
- Spicetify version: 2.13.0
```

### 📝 Description

It just makes them stuck facing sideways. Should we delete it? The css references hashed classes, which is probably why it worked at some point but not anymore. The arrows work fine without it, so that problem probably fixed itself.

**Comment by theRealPadster** [comment]
Oh wait, maybe it still works on Linux, since that's stuck on x.x.84... 🤔

**Comment by CharlieS1103** [comment]
It'll be fixed when css map is

**Comment by kyrie25** [comment]
> It'll be fixed when css map is

Mapped the class as `main-rootlist-expandArrowActive` via spicetify/spicetify-cli#1911.

**Comment by kyrie25** [comment]
Nothing comes to mind, no. Updating the CSS was prob the most stable way to handle this that I could think of.
