### ISSUE TITLE
Fix compatibility for 1.1.94

### ISSUE THREAD

**Issue by xerta555** [spicetify/spicetify-marketplace#335]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.94.872.g7a9200fe
- Spicetify version: 2.13.1
```

### 📝 Description

With the last Spotify version, the Marketplace need to be fixed.
It appear by default like that:
![image](https://user-images.githubusercontent.com/20888017/192043846-8d62ef41-0d09-43c9-9e72-2a1208e3f4e2.png)

I have fix it on my side by playing with `padding-top` CSS rule.

Thanks in advance.

**Comment by kyrie25** [comment]
Resolved via #334
