### ISSUE TITLE
Edit Extensions Themes and custom apps

### ISSUE THREAD

**Issue by Tetrax-10** [spicetify/spicetify-marketplace#336]
### 📝 Provide a description of the new feature

It would be a good feature to implement this.
Eg: Save Playlist extension saves playlist with a Copy name (`Copy of ${playlist.name}`).
I can't edit that in marketplace. So, I need to install it manually. which kinda sucks.
and whenever there is an ext update, that edited extension shouldn't auto update.

**Comment by kyrie25** [comment]
Not possible. All Marketplace assets are fetched remotely, none of them are kept locally and available for edit.

**Comment by Tetrax-10** [comment]
Size limit is 5MB.
![image](https://user-images.githubusercontent.com/75513645/192398670-b4c1a035-87e6-414c-b59f-4c88ba613a5b.png)
this my current local storage size used in spotify.
5MB is like 40k to 50k lines dude

i know codes are fetched remotely just store the edited code in local storage and use it. like custom snippets

**Comment by kyrie25** [comment]
Custom Snippets are very short. You forgot to take account the amount of themes and that Marketplace supports saving image files are preview for snippets, which in itself can easily ramp up space.

**Comment by kyrie25** [comment]
Auto-updating is a feature of Marketplace and we have no reason to remove it just to adapt another feature that has little usage for non-technical users.

**Comment by CharlieS1103** [comment]
Plus we already support the editing of color.ini's form within marketplace as well as the ability to add custom snippets which should be enough for most users.
