### ISSUE TITLE
Use TooltipWrapper for icon buttons

### ISSUE THREAD

**Issue by theRealPadster** [spicetify/spicetify-marketplace#343]
### 📝 Provide a description of the new feature

Any buttons that don't have any text/description should be good imo (Settings/Color Schemes/Install/Remove/etc.)

### ➕ Additional Information

Just not 100% sure about implementing since if the hook breaks, it'll break Marketplace.

**Comment by kyrie25** [comment]
I mean we can make our own component that does conditional checks.
If the component is hooked, pass the button as a child to the Tooltip component and return the `TooltipWrapper` element.
If it doesn't then just return the child element.

**Comment by theRealPadster** [comment]
I like that idea 👍

**Comment by theRealPadster** [comment]
Did we get anywhere on this? I know we added the wrapper component, right?

**Comment by kyrie25** [comment]
> Did we get anywhere on this? I know we added the wrapper component, right?

Charlie used it for his album color extract thing before and all is good so far so we can work on this whenever.
