### ISSUE TITLE
Unable to change color scheme when installing themes via the market place

### ISSUE THREAD

**Issue by NotLimey** [spicetify/spicetify-marketplace#349]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.95.893.g6cf4d40c
- Spicetify version: 2.14.0
```

### 📝 Description

1. Install any theme from the marketplace (Tested with dribblish and sleek)
2. Attempt to change color scheme via terminal `spicetify config color_scheme dark`
3. Run `spicetify apply` - receive success status!🤩
4. Notice that your color scheme has not changed😑

### 📸 Screenshots

![Screenshot 2022-10-14 at 09 58 25](https://user-images.githubusercontent.com/70258183/195794150-a37be4b6-adf7-4092-b6f7-572ce267080c.png)

**Comment by vancromy** [comment]
bump! I experience the same issue when trying to change color scheme for the Sleek theme installed via marketplace

**Comment by kyrie25** [comment]
You can change color schemes for theme installed via Marketplace using the dropdown next to the search bar on Marketplace.

**Comment by NotLimey** [comment]
Hehe woopsi thank you 😅
