### ISSUE TITLE
Updating to 0.8.1 breaks many plugin's functionality (Mac)

### ISSUE THREAD

**Issue by SKDemon820** [spicetify/spicetify-marketplace#351]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.94.872.g7a9200fe
- Spicetify version: 2.13.0
```

### 📝 Description

Suddenly most of my extensions weren't working, so I downgraded Spotify to an old version and noticed that the issue still persisted.  So then I loaded an old backup I took of the spicetify folders and everything was fixed, but I saw the button in the marketplace prompting the 0.8.1 update and upon updating the same thing was happening.  Both the marketplace "Installed" tab and spicetify CLI show things as being installed, but the following extensions weren't actually working:

- Adblock
- Playnext
- Volume percent
- Full album date

The only ones that were working were ones I manually installed through the CLI, like Shuffle+ and Lyrics-Plus.  Themes were working fine (I only tested generic ones without external javascript)

**Comment by SKDemon820** [comment]
I see the issue was closed but it doesn't say exactly why (Idk if it's "wont fix" or "can't reproduce" or whatever) so here an actual video showing it happening


https://user-images.githubusercontent.com/62918850/196274928-8ee71bac-87da-4d8e-90a6-e5f511bab0fa.mp4

**Comment by CharlieS1103** [comment]
@SKDemon820 It's not an issue with marketplace, both of those extensions use css to select elements and hide/ modify them and those css names often change across versions. Do you get audio ads with adblock installed or no?

**Comment by SKDemon820** [comment]
Yes, I was getting audio ads before I loaded the backup to fix it.  And it's the same Spotify version before and after the update so the css names shouldn't be changing, unless you meant a marketplace/spicetify update changes those names for some reason

**Comment by CharlieS1103** [comment]
@SKDemon820 You try updating your spicetify version? you're a few versions behind.

**Comment by SKDemon820** [comment]
That fixed it, that was one of the first things I tried but I was using "update" which apparently just updates CSS instead of "upgrade."  Thank you!
