### ISSUE TITLE
Nothing on the marketplace tab.

### ISSUE THREAD

**Issue by DarkArtz0** [spicetify/spicetify-marketplace#388]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version:Windows
1.1.99.878.g1e4ccc6e
- Spicetify version:Spicetify v2.14.2
```

### 📝 Description

Its just a blank page when i enter the marketplace tab.

### 📸 Screenshots

![Spotify_Free e970c339-7fa8-4ad1-acdd-0dc805a8b0b3              floppabest 🚠](https://user-images.githubusercontent.com/95894740/204724250-4935d082-89c1-4d30-9cbf-86a74fe8c441.png)

**Comment by CharlieS1103** [comment]
Upgrade spicetify and marketplace

**Comment by creightonmcc** [comment]
What's that extensions on the side?
