### ISSUE TITLE
Can't Detect Spotify "prefs" file location.

### ISSUE THREAD

**Issue by creightonmcc** [spicetify/spicetify-marketplace#406]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version:1.1.84
- Spicetify version: v2.15.0
```

### 📝 Description

![1672169226664743702131107244639](https://user-images.githubusercontent.com/119522131/209713590-d8d169ca-8bbb-4ff9-9995-92c201718925.jpg)

**Comment by kyrie25** [comment]
1. Not a Marketplace issue
2. FAQ
