### ISSUE TITLE
Sort extensions by most recent

### ISSUE THREAD

**Issue by Resxt** [spicetify/spicetify-marketplace#412]
### 📝 Provide a description of the new feature

Within the Marketplace settings (or next to the setting button), having a way to sort extensions by most recent would be nice to see if there are new extensions that you might be interested in.

The best way to do that would be to get the extension's release date instead of the repository's last update date since some repositories contain multiple extensions.

The way I see it, it could either be a dropdown menu to choose how to sort extensions (highest/lowest starts count, most recent etc) within the Marketplace settings popup or next to the search bar in the Marketplace main menu.

I think it would be a nice addition to take a quick look at the Marketplace from time to time and quickly see the new extensions released that you might be interested in, instead of having them at the bottom of the page or, even worse, hard to find when it's from a repository that already has a good amount of stars which then makes the extension appear in the middle of the extensions list which is hard for the user to really find when an extension is released/new

**Comment by CharlieS1103** [comment]
Yeah we've been wanting to add sorting options for a while, I think we already have an issue for it so maybe just add this as a comment to that
