### ISSUE TITLE
I added a lot of my own css snippets, I forgot to back them up separately.is there any way to restore the css snippets?

### ISSUE THREAD

**Issue by youthyan** [spicetify/spicetify-marketplace#417]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
Spotify macOS (Intel) 版
1.2.3.1115.gd61a8f5c
Spicetify v2.14.3
```

### 📝 Description

I added a lot of my own css snippets, I forgot to back them up separately.
but today I opened spotify and found that the css snippets became blank, I don’t know why they were automatically deleted, I am very frustrated.
is there any way to restore the css snippets?
I don’t want to rewrite the css, is there a way to help me?
please.

### 📸 Screenshots

<img width="223" alt="截屏2023-01-24 上午7 41 32" src="https://user-images.githubusercontent.com/105373147/214178205-df2b6baa-fa38-4476-9a66-0ffdc626129f.png">
<img width="752" alt="截屏2023-01-24 上午7 41 22" src="https://user-images.githubusercontent.com/105373147/214178214-6a767769-c890-459f-b32f-ebdc9315cdfd.png">

**Comment by rxri** [comment]
No, sorry. Also it's question about marketplace not related to CLI

**Comment by rxri** [comment]
No, that's not possible, sorry

**Comment by theRealPadster** [comment]
For future reference, all marketplace data is stored in Spotify cache essentially. So don't clear the cache, or if you do, make a backup of your settings first
