### ISSUE TITLE
icon play are buggy

### ISSUE THREAD

**Issue by TukangM** [spicetify/spicetify-marketplace#428]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version:1.2.4.912.g949d5fd0
- Spicetify version:2.16.1
```

### 📝 Description

1.i install spotify
2. install spotify cli windows powershell
3. install spotify marketplace windows pwsh powershell, then spicetify apply and open the spotify
4. and icon play are buggy

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/91467886/216744010-a63f32be-2a5b-44ed-8d34-539ed6adb43b.png)

**Comment by kyrie25** [comment]
Remove all extensions. Not a Marketplace issue.

**Comment by TukangM** [comment]
> Remove all extensions. Not a Marketplace issue.

hmm. its fresh install. no installed extension
