### ISSUE TITLE
Running auto install ps1 script from this repo doesn't install the latest release of marketplace

### ISSUE THREAD

**Issue by jawdropper16** [spicetify/spicetify-marketplace#431]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
Spotify for Windows
1.2.2.582.gfae9c59b
Spicetify v2.16.1
Theme: Galaxy / base
Extensions: skipStats.js, shuffle+, shuffleplus.js, genre.js, featureshuffle.js, enhancePlus.js, playEnhancedSongs.js, goToSong.js, listPlaylistsWithSong.js, galaxy.js
Custom apps: marketplace
```

### 📝 Description

1. Run script from this github repo: 
Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/spicetify/spicetify-marketplace/main/resources/install.ps1" | Invoke-Expression
![image](https://user-images.githubusercontent.com/104870012/216838317-c69d5dbb-1736-41c1-8fa9-d7d7dd80634d.png)

2. Go to this path:
C:\Users\"Username"\AppData\Roaming\spicetify\CustomApps
![image](https://user-images.githubusercontent.com/104870012/216838419-ef75e272-4bd1-4920-b0d5-01760b10c39c.png)

3. Check the files and see that they all are using release v0.8.4, and not v0.8.5.
![image](https://user-images.githubusercontent.com/104870012/216838586-646e984c-317c-4a92-8e8f-1328b500b513.png)

4. Cry
![emoji-disintergrating](https://user-images.githubusercontent.com/104870012/216838754-95c4f590-095b-4fde-9e1b-a637ec97b57c.gif)

**Comment by jawdropper16** [comment]
I think just turning
https://api.github.com/repos/spicetify/spicetify-marketplace/releases/tags/v0.8.4
into
https://api.github.com/repos/spicetify/spicetify-marketplace/releases/tags/v0.8.5
fixes it lol

**Comment by theRealPadster** [comment]
It is the latest version, I just forgot to bump the version number when I made the release. We will fix. You can ignore the error for now.

**Comment by jawdropper16** [comment]
> It is the latest version, I just forgot to bump the version number when I made the release. We will fix. You can ignore the error for now.

I just changed all the version numbers from 0.8.4 to 0.8.5 and it works, also I had to change the name of the marketplace folder, but I got it working.
![image](https://user-images.githubusercontent.com/104870012/216839937-8fc8ad3c-340f-4703-a847-ccbed6b3aa6f.png)

**Comment by jawdropper16** [comment]
[marketplace_0.8.5.zip](https://github.com/spicetify/spicetify-marketplace/files/10611934/marketplace_0.8.5.zip)
Here

**Comment by theRealPadster** [comment]
I updated the tag and release and it should have the correct version number. Please give it another try, and reopen the issue if it doesn't work.
