### ISSUE TITLE
Spicetify Marketplace does not load

### ISSUE THREAD

**Issue by Teenarp2003** [spicetify/spicetify-marketplace#432]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version:1.1.84.716
- Spicetify version:2.16.1
```

### 📝 Description

Spicetify Marketplace stopped loading since december 2022. 
Openeing the marketplace tab shows an empty page with load more button.. on clicking the koad more button it just shows a loading symbol.

And for some reason running the install script using curl does nothing.. curl is unresponsive.. any help is appreciated..

**Comment by rxri** [comment]
1.1.84 isn't supported by spicetify v2.16.1. Please update your spotify to use latest version of marketplace

**Comment by theRealPadster** [comment]
Are you able to update to Spotify 1.1.99? [AUR](https://aur.archlinux.org/packages/spotify-edge) package here, not sure about other distros.

**Comment by theRealPadster** [comment]
The AUR package is more up to date. Snap is newer, but you can't use snap with spicetify anyways. I don't know how you'd get a newer one on other distros. Spotify is really bad for Linux support and is always outdated

**Comment by Teenarp2003** [comment]
AUR is at version 1.1.84.. i checked the spotify official repository and its at 84.. so nothing to do other than wait..

**Comment by rxri** [comment]
Use either [spotify-snapstore](https://aur.archlinux.org/packages/spotify-snapstore) or [spotify-edge](https://aur.archlinux.org/packages/spotify-edge) package for 1.1.99
