### ISSUE TITLE
Marketplace button not showing in new Spotify UI

### ISSUE THREAD

**Issue by Astrow25** [spicetify/spicetify-marketplace#439]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.5.954.gf42f9f0a
- Spicetify version: v2.16.1
```

### 📝 Description

Marketplace button not showing in new Spotify UI

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/76118368/219517065-f4dd564a-491d-49ee-9d26-9ba0b6657203.png)

**Comment by kyrie25** [comment]
This is not a Marketplace issue.
Anything listed in Experimental Features are not meant to be released to the public, that includes the new UI.
As such we won't be adding support for it until they push it for everyone.
