### ISSUE TITLE
Play/pause button completely disappeared 

### ISSUE THREAD

**Issue by B1ruBiru** [spicetify/spicetify-marketplace#441]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.5.1006.g22820f93
- Spicetify version: Spicetify v2.16.1
```

### 📝 Description

My play button suddenly disappeared, and it's the only thing missing, at least I haven't noticed anything else.

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/123217584/220457822-3fb97501-d1bb-4af6-b740-a86ea3bb8ccc.png)

**Comment by kyrie25** [comment]
Theme issue.
