### ISSUE TITLE
Spicetify Marketplace not showing up

### ISSUE THREAD

**Issue by Pejsek34** [spicetify/spicetify-marketplace#453]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.6.863.ge7902f05
- Spicetify version: 2.16.2
```

### 📝 Description

Recorded behavior: When I launch Spotify (spiced up), there is no MarketPlace. Spicetify is active, because I have the option to "Sidebar config", but there is no Marketplace (shown on the screenshot attached bellow) 
Expected behavior: I have the option to add Marketplace when I turn on Sidebar config

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/88139473/224572428-eff73187-3c51-4818-bb01-83778e37594d.png)

**Comment by Pejsek34** [comment]
Solved in #439, I did not notice

**Comment by theRealPadster** [comment]
Did you install the marketplace app?

**Comment by kyrie25** [comment]
Marketplace is not a built-in app, you need to install it.
https://github.com/spicetify/spicetify-marketplace/wiki/Installation
