### ISSUE TITLE
Add Marketplace version to settings dialog

### ISSUE THREAD

**Issue by theRealPadster** [spicetify/spicetify-marketplace#457]
### 📝 Provide a description of the new feature

<s>This would probably be a cli thing, idk. Feel free to move issue if needed</s>

Original issue was to add Marketplace version to Spotify "About" dialog, but we decided to put the Marketplace version in the Marketplace Settings dialog instead.

**Comment by Poopooracoocoo** [comment]
Does the Spicetify Marketplace version appear in `config.ini`s too? Would make support much easier as people could just ask them to post that and it'll show lots of relevant information.

**Comment by theRealPadster** [comment]
> Does the Spicetify Marketplace version appear in `config.ini`s too? Would make support much easier as people could just ask them to post that and it'll show lots of relevant information.

It does not. As of now, Marketplace is not interested with CLI at all. It's just a custom app, albeit somewhat official.

**Comment by CharlieS1103** [comment]
@theRealPadster couldn't we also just use a mutation observer and add the info ourselves?

**Comment by theRealPadster** [comment]
> @theRealPadster couldn't we also just use a mutation observer and add the info ourselves?

Yes but that adds overhead, more stuff running in the background etc. If possible, I'd like to avoid that, to keep things light.
