### ISSUE TITLE
"Something went Wrong. Try Reloading the Page." but when I reload, nothing happens and Marketplace still doesn't appear

### ISSUE THREAD

**Issue by cinnamintRoll** [spicetify/spicetify-marketplace#480]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
Spotify for Windows: 1.2.9.743.g85d9593d
Spicetify: v2.16.1
```

### 📝 Description

Basically what the title said.

"Something went Wrong. Try Reloading the Page." but when I reload, nothing happens and the error is still there no matter how many times I reload. I tried reinstalling marketplace via Powershell but it still does not work.

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/96367858/232364794-8705d7ff-a56f-4469-807b-7e407a798210.png)

**Comment by ashercs** [comment]
Why was this closed with no fix? I still am having this error.
