### ISSUE TITLE
unable to install extensions

### ISSUE THREAD

**Issue by TrippyCode** [spicetify/spicetify-marketplace#483]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.9.743-1
- Spicetify version: 2.17.2-1 (installed via package manager, however `spicetify -v` command shows `Dev`)
- OS: Arch linux (garuda) (I noticed the same issue on windows too)
```

### 📝 Description

1.  install spotify as recommended
2. give spicetify permissions for required directories
3. install spicetify using arch package manager
4. install themes and snippets from spicetify marketplace: works as expected
5. install extensions: 
expected: install extension after clicking on install and reload now buttons.
result: extension is not installed
however manually installing one extension at a time from command line works as expected.

**Comment by rxri** [comment]
Not related to cli. Please take a look on our discord server for potential resolve of your issue
