### ISSUE TITLE
Marketplace not loading; getting "Something went wrong" message

### ISSUE THREAD

**Issue by user9713** [spicetify/spicetify-marketplace#488]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.10.760
- Spicetify version: 2.16.1
```

### 📝 Description

The Marketplace won't load up for me. Whenever I click it, I only get a message stating "Something went wrong. Try reloading the page."

It used to work, but hasn't worked in the past 2-3 Spotify updates. I always run `spicetify backup apply` after every Spotify update.

Reproducing is easy, just click on "Marketplace" in the upper left sidebar.

Other info:
* I haven't find anyone else experiencing the issue
* OS: Windows 10

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-marketplace/assets/41145147/8a8514cf-6acb-4217-8338-fbb886881c89)

**Comment by kyrie25** [comment]
Outdated Spicetify version. Run `spicetify upgrade` then `spicetify restore backup apply`

**Comment by cougarten** [comment]
would be great to have a single command for upgrade, restore, backup, apply
