### ISSUE TITLE
Snippets not updating correctly, should check GitHub for changes

### ISSUE THREAD

**Issue by Fadexz** [spicetify/spicetify-marketplace#492]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.11.916.geb595a67
- Spicetify version: 2.18.1
```

### 📝 Description

It would be great if snippets could be updated to correctly update once a change as been made on GitHub.
I was told (by @theRealPadster) that it checks the local marketplace files, however no matter what I seem to do I can never seem to get my snippet to show in the marketplace, I've tried deleting files multiple times, but I must be missing something.
For reference, it is my Rounded Images snippet which doesn't appear.

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-marketplace/assets/37004055/b484a4ba-eb9b-4752-b40f-11b860f199e7)

**Comment by kyrie25** [comment]
Snippets are stored locally and on releases.
This was deliberately made, commits on the current development version will be snipped on the next release
