### ISSUE TITLE
Add (implement) sorting options

### ISSUE THREAD

**Issue by theRealPadster** [spicetify/spicetify-marketplace#5]
Maybe use the "top/new/rising/etc" dropdown for github sort options? e.g. number of star or downloads

![image](https://user-images.githubusercontent.com/1565883/134825923-c38d2a56-7757-46a9-bac1-e9bec86cedb5.png)

**Comment by Satanarious** [comment]
You guys can take inspiration from betterdiscord:

Here's the sorting drop-down:
![image](https://user-images.githubusercontent.com/42642682/226621920-5b21f03c-6be1-49ed-8faa-c5eafc11aaba.png)
They also have a tag filter:
![image](https://user-images.githubusercontent.com/42642682/226622022-fd6f1876-44d7-49b6-aa47-0bd8fb1d0031.png)

**Comment by Satanarious** [comment]
You guys can take inspiration from betterdiscord :
![image](https://user-images.githubusercontent.com/42642682/226621920-5b21f03c-6be1-49ed-8faa-c5eafc11aaba.png)
They also have a tag filter:
![image](https://user-images.githubusercontent.com/42642682/226622022-fd6f1876-44d7-49b6-aa47-0bd8fb1d0031.png)

**Comment by SunsetTechuila** [comment]
@theRealPadster i guess this one can be closed?
