### ISSUE TITLE
Marketplace filters

### ISSUE THREAD

**Issue by urthurao** [spicetify/spicetify-marketplace#501]
### 📝 Provide a description of the new feature

Sort marketplace items by stars count (highest/ lowest), A-Z, Z-A, newest/ oldest, etc.

### ➕ Additional Information

Especially helpful would be the "newest" filter. I want to be able to see what new items people have added to the marketplace so I can keep up-to-date with the community's latest additions to Spicetify.

**Comment by kyrie25** [comment]
Duplicate of #5
