### ISSUE TITLE
Left sidebar and song cover missing

### ISSUE THREAD

**Issue by glisteningcoder** [spicetify/spicetify-marketplace#508]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
Spotify for Windows
1.2.12.902.g1924b088
Spicetify v2.19.0
Theme: Comfy / Comfy
Extensions: autoSkipExplicit.js, autoSkipVideo.js, fullAppDisplay.js, webnowplaying.js, popupLyrics.js, loopyLoop.js, queueAll.js, djMode.js, shuffle+.js, trashbin.js, keyboardShortcut.js, rotateTurntable.js, Vibrant.min.js, default-dynamic.js, featureshuffle.js, songstats.js, wikify.js, adblock.js, fixEnhance.js, phraseToPlaylist.js, skipStats.js, listPlaylistsWithSong.js, goToSong.js, fullAlbumDate.js, playlistIntersection.js, savePlaylistsWrapper.js, autoSkipWrapper.js, playNextWrapper.js, sortByPlayCount.js, spotifyBackup.js, seekSong.js, playEnhancedSongs.js, romaji_lyrics.js, power-bar.js, genre.js, group-session.js, lastfm.js, copytoclipboard2.js, volumePercentageWrapper.js, volume-profiles.js, starRatings.js, QueueTime.js, SleepTimer.js, rym.js, part_selector.js, startup-autoplay.js, friendlikes.js, cacheCleaner.js, copyPlaylistInfo.js, extended-copy.js, formatColors.js, fullScreenWrapper.js, hot-cues.js, share-on-twitter.js, aoty.js, enhancePlus.js, css-editor.js, listenTogether.js, sortByRating.js, startup-page.js, playOnYouTube.js, star-ratings.js, djinfo.js, romaji-convert.js, LuckyLP.js, noTrackingLinks.js, comfy.js
Custom apps: reddit, lyrics-plus, new-releases, marketplace, name-that-tune, combined-playlists
xpui_2023-05-22_1684749980124_1924b08
cef_112.3.0+gb09c4ca+chromium-112.0.5615.165
```

### 📝 Description

So right now I am unable to retrieve the left sidebar and the cover image is missing as well. It almost seems like it got my screen dimension wrong and the whole sidebar got detruded in there.

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-marketplace/assets/66782694/48448895-8076-410e-b4c9-be34fdd24a0f)

**Comment by CharlieS1103** [comment]
@ohitstom

**Comment by ohitstom** [comment]
> @ohitstom 

not a comfy issue he has multiple extensions enabled from other themes

**Comment by CharlieS1103** [comment]
@glisteningcoder go through all your extensions and make sure they're all necessary + up to date

**Comment by glisteningcoder** [comment]
So after I enable DevTools to see where was my sidebar, I found out that there was just a silver of that left sidebar and I was still be able to click on these menus. After looking through all of my installed snippets, extensions and themes, I found out that Hover Sidebar was the culprit. Still thank you guys a lot @CharlieS1103 @ohitstom
