### ISSUE TITLE
Whatever you did completely broke it (at least for me)

### ISSUE THREAD

**Issue by PaulWentzel** [spicetify/spicetify-marketplace#512]
Whatever you did completely broke it (at least for me)
Spent the last 1-2 hours trying to figure out what was wrong.
Left side panel didnt want to show up whatsoever.
Did fresh install of everything and so on.
Now i somehow noticed that i could click on the very left and landed in marketplace where i was able to remove hover panels.
Enabling it back brings the problem back.

https://github.com/spicetify/spicetify-marketplace/assets/100777359/d4cfabf7-9256-4022-8227-51500af7b132

_Originally posted by @PaulWentzel in https://github.com/spicetify/spicetify-marketplace/issues/511#issuecomment-1579450795_

**Comment by rxri** [comment]
please use issue template
