### ISSUE TITLE
Marketplace broken after logging in and out of another account

### ISSUE THREAD

**Issue by karimawii** [spicetify/spicetify-marketplace#513]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
Spotify for Windows
1.2.12.902.g1924b088
Spicetify v2.20.0
Theme: marketplace / Karimawi
Extensions: fullAppDisplayMod.js, goToSong.js, fullAlbumDate.js, power-bar.js, autoSkipWrapper.js, volumePercentageWrapper.js, volume-profiles.js, playNextWrapper.js, genre.js, showQueueDuration.js, copy-track-titles.js, playlistIntersection.js, startup-page.js, group-session.js, SleepTimer.js, skipOrPlayLikedSongs.js, spotifyBackup.js, savePlaylistsWrapper.js, QueueTime.js, sortByPlayCount.js, romaja_lyrics.js, quick-add-to-playlist.js, noTrackingLinks.js, romaji-convert.js, songwhip.js, playOnYouTube.js, who-added.js, webnowplaying-redux.js, imageToClipboard.js, playing-source.js, extended-copy.js, cacheCleaner.js, beautiful-lyrics.js, imageOpener.js, romaji_lyrics.js
Custom apps: marketplace
```

### 📝 Description

Extension are not loading at all, manually installed extensions do run, but Marketplace extensions and theme.js don't run, tried reinstalling Spotify, Spicetify and marketplace multiple times, the previously installed extensions are just stuck in the installed tab, idk where they're cached from, but they ain't working, I tried the reset button in the settings a lot of times but it doesn't uninstall or reset a thing.

### 📸 Screenshots

https://github.com/spicetify/spicetify-marketplace/assets/69881381/1c7b8ea3-6308-42f0-a297-e5f5a0e57143

**Comment by karimawii** [comment]
also trying to install new extensions from the marketplace only puts them in the installed tab, they don't work either.

**Comment by karimawii** [comment]
I also tried re-logging in to the other account to see if the extensions work or try to reset, neither of those worked

**Comment by CharlieS1103** [comment]
If I had to guess it might be due to the crazy amount of extensions you have. Could be trying to load them too quickly and getting ratelimted. Try uninstalling some that you don't use

**Comment by karimawii** [comment]
Nope, I uninstalled all of them and just kept Volume Profiles and Sleep Timer, still did not work, there's clearly no theme (just the color profile) and there's no volume profiles or sleep timer down at the bottom.
![image](https://github.com/spicetify/spicetify-marketplace/assets/69881381/7e906c3a-b37e-45a6-8aab-723758850486)

**Comment by kyrie25** [comment]
Most likely a network issue with JSDelivr as this occurs with most users recently, try using a VPN.

**Comment by karimawii** [comment]
Yeah, it is, wow, I would've never thought of that, do you think there might be an alternative to the VPN? Cause I can't use a VPN all the time.

**Comment by kyrie25** [comment]
You could look into proxies, DNS, etc. for your network configurations (e.g. Google's public DNS)

**Comment by karimawii** [comment]
@CharlieS1103 @kyrie25 
Thought this would help out a bunch of people and will probably save you guys a ton of time trying to suggest a solution, 

[<img alt="Click to go to message in Spicetify Discord" src="https://github.com/spicetify/spicetify-marketplace/assets/69881381/9f9b51d4-12e5-4cb7-8c8a-ef9bbd87cb2d" />](https://discord.com/channels/842219447716151306/1116428095205933128/1119878780907954227)

This worked like a charm for me, and you just turn it on and forget about it
Cloudflare's WARP: https://1.1.1.1/
