### ISSUE TITLE
extensions not working anymore

### ISSUE THREAD

**Issue by Mechful** [spicetify/spicetify-marketplace#514]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
Spotify for Windows 11 
1.2.12.902.g1924b088

Spicetify
v2.20.0

Spicetify marketplace 
0.8.6
```

### 📝 Description

extensions not working anymore. I check the extension folder I don't see any file downloaded and installed. it shows In Marketplace UI that the extension was successfully installed. but its not

I have to copy js files to the extension folder manually and install it via PowerShell 

I reinstalled everything. marketplace, specify, and Spotify the problem still exists

**Comment by kyrie25** [comment]
Network issue, use a VPN

**Comment by karimawii** [comment]
@Mechful https://github.com/spicetify/spicetify-marketplace/issues/513#issuecomment-1595996050
