### ISSUE TITLE
Unable to install themes

### ISSUE THREAD

**Issue by thegoldknight** [spicetify/spicetify-marketplace#521]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.13.661.ga588f749
- Spicetify version: v2.20.0
```

### 📝 Description

Unable to install themes. I've tried quitting/reopening, and I've tried reinstalling Spicetify. 

### 📸 Screenshots

https://github.com/spicetify/spicetify-marketplace/assets/135397968/711ed9bd-61fa-4f6d-9733-7c52ea8ca027

**Comment by kyrie25** [comment]
Reset and reinstall Marketplace.

**Comment by thegoldknight** [comment]
I uninstalled Spicetify and Marketplace, and reinstalled them again. Still doesn't work.

**Comment by kyrie25** [comment]
Reset not only reinstall.

**Comment by thegoldknight** [comment]
> Reset not only reinstall. 
And how do I do that?

> Also issues are not support tickets.
I'm sorry; I'm new to github and I don't really know how everything works.

**Comment by thegoldknight** [comment]
Ok I restored Spicetify and reinstalled, and now I can only install certain themes but not the ones I want. Would the internet connection be a factor?

**Comment by CharlieS1103** [comment]
@thegoldknight If you're from Egpyt you need to install it manually.

**Comment by thegoldknight** [comment]
> @thegoldknight If you're from Egpyt you need to install it manually.

I'm not in Egypt...It used to work and it suddenly stopped working. And now I can't install extensions.

**Comment by CharlieS1103** [comment]
Reset marketplace, should be a guide somewhere on our GitHub

**Comment by thegoldknight** [comment]
Ok, I've uninstalled Spicetify by running 
`spicetify restore
rm -rf ~/.spicetify
rm -rf ~/.config/spicetify`

and then reinstalling with
`curl -fsSL https://raw.githubusercontent.com/spicetify/spicetify-cli/master/install.sh | sh`
and 
`curl -fsSL https://raw.githubusercontent.com/spicetify/spicetify-marketplace/main/resources/install.sh | sh`

This allows me to install the first few themes, but nothing else. Is this what you mean by reseting marketplace?
