### ISSUE TITLE
Unable to load marketplace

### ISSUE THREAD

**Issue by ANii693** [spicetify/spicetify-marketplace#522]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
Spotify for Windows
1.2.13.661.ga588f749
Spicetify v2.20.1
```

### 📝 Description

I'm encountering an issue where the marketplace is not loading, the app themes and extensions are not functioning. I'm unable to identify the cause of the problem.

I have attached the ss how it looks

### 📸 Screenshots

![Screenshot (302)](https://github.com/spicetify/spicetify-marketplace/assets/118979320/ceb7b750-b861-48ca-b4ec-ca25c76d13d3)
![Screenshot (303)](https://github.com/spicetify/spicetify-marketplace/assets/118979320/6af55d1b-838b-4bd2-ac9b-2a747cd20f8b)
![Screenshot (304)](https://github.com/spicetify/spicetify-marketplace/assets/118979320/f711e3aa-b2d1-4b3c-9659-6d4aeb1799b7)
![Screenshot (305)](https://github.com/spicetify/spicetify-marketplace/assets/118979320/2f22ce32-5932-4cc2-af49-7a6708eae9aa)

**Comment by kyrie25** [comment]
Network issue, try using a VPN and reinstall Marketplace.
