### ISSUE TITLE
New releases page issue

### ISSUE THREAD

**Issue by 840r4uwjefi98g0iekopf** [spicetify/spicetify-marketplace#530]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.14
- Spicetify version: 2.20.2
```

### 📝 Description

Opening the New Releases app gives me the page "Something went wrong try reloading the page" and reloading the page doesn't help. I did a clean reinstall of both Spotify and Spicetify but the issue persists on the new versions of Spotify/Spicetify. Attached a screenshot of the Devtools errors

### 📸 Screenshots

![Screenshot](https://github.com/spicetify/spicetify-marketplace/assets/116382654/b559a151-1ef4-4226-b04b-5e6d0abd8f26)

**Comment by rxri** [comment]
Will be fixed in next release (isn't related to new releases only)
