### ISSUE TITLE
Please block the Adblock extension

### ISSUE THREAD

**Issue by symbion6** [spicetify/spicetify-marketplace#539]
### 🔗 Extension Link

https://github.com/CharlieS1103/spicetify-extensions

### 📝 Describe the Issue

The Adblock extension blocks ads in Spotify, thereby decreasing their revenue.
So far, Spotify has been kind to Spicetify.
If there's a big reason for them to block Spicetify, it's because of this.
This endangers not only the users that are profiting from the Adblock extension, but also all other Spicetify users.

Please block this extension.

**Comment by ohitstom** [comment]
get real

**Comment by SunsetTechuila** [comment]
Most based spicetify user

**Comment by polarnasu** [comment]
Lol nah, fuck ads

**Comment by CharlieS1103** [comment]
@symbion6 you recognize I made this one too

**Comment by symbion6** [comment]
@CharlieS1103 No, I did not know that, obviously. Did you create Spicetify itself also?

For the rest of the replies....no need to be rude here.
I'm just suggesting something that could make us enjoy Spicetify even longer.

**Comment by rxri** [comment]
He did not create spicetify, does it matter though? As Spicetify developer, we will not block Charlie's adblock extension

**Comment by symbion6** [comment]
Unbelievable how rude and attacking everyone is here.
As a thank you I've just stopped my monthly contribution through Open Source Collective.
Have a great day everyone.

**Comment by rxri** [comment]
> Unbelievable how rude and attacking everyone is here.

I'm not rude towards you but only informing that it will not happen.Your arguments are not true at all, that's why we will not even discuss the possibility of blocking it.
You also decide how you want to spend your money, if you don't want to support us - that's completely fine

**Comment by symbion6** [comment]
Then someone could have replied explaining that (that my arguments are not true), instead of just closing the issue and other users and contributors acting like 3 years olds by replying with "most based spicetify user" and "seethe and cope".

**Comment by SunsetTechuila** [comment]
Absolutely based too

**Comment by polarnasu** [comment]
Lol just shut up already 

> Then someone could have replied explaining that (that my arguments are not true), instead of just closing the issue and other users and contributors acting like 3 years olds by replying with "most based spicetify user" and "seethe and cope".

Boy you sure whine a lot, anyways I'll keep enjoying spicetify without ads!

**Comment by CharlieS1103** [comment]
> @CharlieS1103 No, I did not know that, obviously. Did you create Spicetify itself also?
> 
> For the rest of the replies....no need to be rude here. I'm just suggesting something that could make us enjoy Spicetify even longer.

I do recognize that some of the replies were rude, I should have removed those earlier and the people who made them don't represent Spicetify.

**Comment by rxri** [comment]
@symbion6, please check this response that I wanted to include in issue that you created on charlie's repo some time ago;

> But if you add an extension to block ads, it's going in the wrong direction.

There are a number of adblockers that can disable Spotify ads by redirecting some of Spotify's domains to localhost in DNS settings or modyfing xpui. Since these modifications do no harm Spotify (if they would, they would already be blocked), the Spicetify team is not going to block them.

> If there's a big reason for them to block Spicetify, it's because of this.

It's not quite true to say that this would be the main reason blocking Spicetify. Other adblockers have been around longer than Spicetify or this extension. Additionally, compared to all of Spotify, Spicetify's user base is quite small. Recently, Spotify added an experiment that would disable the negative durations in Esperanto ads API, which was enabled by default in version 1.2.13, iirc. That suggests Spotify is aware of it, but this experiment shows that they are making attempts to block it over going the legal route, so they are coming up with workarounds to block it in some way. The Spicetify team did not create or distribute the adblock extension. Adblock extension is not the reason for Spotify to even make cease and desist towards spicetify project. Spotify's Terms of Service make no mention of the ban on client modification.

> Please remove this feature, please respect Spotify's business model and please don't put other Spicetify users in danger by keeping this extension online, thank you.

As I said earlier, the fact that this extension exists is not harmful to any users simply because we have discovered ways to change how ads operate and remove/skip them with their own API

**Comment by symbion6** [comment]
I appreciate the clarification. If there's no explicit prohibition on client modification, that certainly tells something.

However, I disagree with the notion that removing ads is harmless to Spotify. Aside from losing out on ad revenue, ads play a critical role in motivating users to opt for a premium subscription. By removing ads, this incentive is effectively nullified.

This doesn't just impact Spotify, but also the artists who share their music on the platform. 
I don't believe that's fair to them.

It's my experience that damaging someone's revenue stream, regardless of the magnitude, is never a good move. It's often has negative consequences, sooner or later.

Just my 2 cents....

I hope we can continue to appreciate Spicetify for as long as feasible. Thank you for bringing it to life!

**Comment by polarnasu** [comment]
> I appreciate the clarification. If there's no explicit prohibition on client modification, that certainly tells something.
> 
> However, I disagree with the notion that removing ads is harmless to Spotify. Aside from losing out on ad revenue, ads play a critical role in motivating users to opt for a premium subscription. By removing ads, this incentive is effectively nullified.
> 
> This doesn't just impact Spotify, but also the artists who share their music on the platform. I don't believe that's fair to them.
> 
> It's my experience that damaging someone's revenue stream, regardless of the magnitude, is never a good move. It often has negative consequences, sooner or later.
> 
> Just my 2 cents....
> 
> I hope we can continue to appreciate Spicetify for as long as feasible. Thank you for bringing it to life!

Damn wait til you find out about others like me who also use ublock origin and sponsorblock for YouTube etc to block all ads 🤣

**Comment by ohitstom** [comment]
> I appreciate the clarification. If there's no explicit prohibition on client modification, that certainly tells something.
> 
> However, I disagree with the notion that removing ads is harmless to Spotify. Aside from losing out on ad revenue, ads play a critical role in motivating users to opt for a premium subscription. By removing ads, this incentive is effectively nullified.
> 
> This doesn't just impact Spotify, but also the artists who share their music on the platform. 
> I don't believe that's fair to them.
> 
> It's my experience that damaging someone's revenue stream, regardless of the magnitude, is never a good move. It often has negative consequences, sooner or later.
> 
> Just my 2 cents....
> 
> I hope we can continue to appreciate Spicetify for as long as feasible. Thank you for bringing it to life!

This doesn't really hurt artists Spotify pay per stream not per ad playback, and once again Spotify isn't the only ones to provide this service. If Spotify were to take the legal route they are highly unlikely to target spicetify itself but instead the adblocking extension.

**Comment by symbion6** [comment]
> This doesn't really hurt artists Spotify pay per stream not per ad playback

Without revenue from ads and premium subscriptions, there's no money to pay the artists per stream...
