### ISSUE TITLE
Blank Screen/Not loading 

### ISSUE THREAD

**Issue by Diveball** [spicetify/spicetify-marketplace#553]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version:
- Spicetify version:
```

### 📝 Description

As you can see from the screenshot whenever i load up spotify with spicetify nothing loads, but if I load spotify without spicetify everthing works fine.

### 📸 Screenshots

![Spicetify](https://github.com/spicetify/spicetify-marketplace/assets/136278903/3e223519-b347-4872-9e1a-59a8592adffd)

**Comment by kyrie25** [comment]
Not a Marketplace issue. GitHub issues are not support tickets.

Install Spotify using the installer from their website, run `spicetify upgrade` then `spicetify backup apply`.
