### ISSUE TITLE
my ad block dose not block any thing 

### ISSUE THREAD

**Issue by Ayman-alshafy** [spicetify/spicetify-marketplace#558]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version:
- Spicetify version:2.22.1
```

### 📝 Description

.

### 📸 Screenshots

.

**Comment by Aimarekin** [comment]
Not an issue with the marketplace, go to the extension's repo [CharlieS1103/spicetify-extensions](https://github.com/CharlieS1103/spicetify-extensions)

**Comment by kyrie25** [comment]
Not a Marketplace issue
