### ISSUE TITLE
With the new 0.8.8 update, nothing except snippets is working for me

### ISSUE THREAD

**Issue by SKDemon820** [spicetify/spicetify-marketplace#561]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.94.872.g7a9200fe
- Spicetify version: 2.22.1
- OS: MacOS Monterey 12.5
```

### 📝 Description

After upgrading to the new marketplace update, nothing except snippets work.  Extensions and themes show as downloaded, but don't actually alter the Spotify app even if I remove then reinstall them.  Snippets and custom CSS work as expected with no issues.  Downgrading to marketplace v0.8.7 fixes the issue.

The issue occurs both on the latest Spicetify version and the older version recommend for dated Spotify versions.  I understand that Spicetify (and presumably marketplace) aim to support the latest Spotify version and afaik don't go out of their way for old versions — if this issue is due to my older Spotify version just lmk and I can stay on 0.8.7 if there aren't plans to support it.

### 📸 Screenshots

https://github.com/spicetify/spicetify-marketplace/assets/62918850/dc6d0fb5-1991-433d-b18c-49a5389fdcac

**Comment by rxri** [comment]
Spotify 1.1.94 isn't supported with v2.22.1 as it's said on release page in compatibility section:
![image](https://github.com/spicetify/spicetify-marketplace/assets/9348108/940965a7-9c28-438b-acdd-60a7d680eeb2)
Everything under 1.2.0 is unsupported
