### ISSUE TITLE
Lyrics tag/label

### ISSUE THREAD

**Issue by Kjay7** [spicetify/spicetify-marketplace#563]
### 📝 Provide a description of the new feature

A small lyrics tag/label to show up beside songs in playlist/singles/albums would be very helpful. Similar to how the tag shows up on mobile. Instead of playing the songs to figure out if lyrics are available. I am a curator for lyrics on Musixmatch so this would be a guide/indicator for what song I need to add lyrics for.

**Comment by kyrie25** [comment]
Not a Marketplace isues. Suggest for extension ideas in the Discord server.
