### ISSUE TITLE
not working v0.8.8

### ISSUE THREAD

**Issue by onijuiku** [spicetify/spicetify-marketplace#573]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version:1.2.17.834.g26ee1129
- Spicetify version:2.22.1
```

### 📝 Description

ive tried uninstalling and reinstalling it, running backups, etc...
i cant download extenstions, only the snippets works.
ive tried doing everything even seeing if it was me, and ive come to the fact that it wasn't.
ive put a screenshot showing that i got volume percentage and its not there.

### 📸 Screenshots

![Screenshot (1)](https://github.com/spicetify/spicetify-marketplace/assets/141508401/352b32da-426a-45b2-a617-9854ede9259a)

**Comment by onijuiku** [comment]
to add, it was like this before the spotify update

**Comment by onijuiku** [comment]
add, it was like this before the spotify update

**Comment by kyrie25** [comment]
Use a VPN.

**Comment by onijuiku** [comment]
ive tried using vpn, i use express vpn, still no work

**Comment by kyrie25** [comment]
Use another service/provider.

Issues are not for support, make a ticket on our Discord server.
