### ISSUE TITLE
Add an option to disable extensions without uninstalling them

### ISSUE THREAD

**Issue by Hrushal-Nikhare** [spicetify/spicetify-marketplace#581]
### 📝 Provide a description of the new feature

I would like to suggest the addition of a new feature to our software that allows users to disable extensions without the need to uninstall them. Currently, when a user wants to temporarily stop using an extension, they have to completely uninstall it, which can be inconvenient if they later want to reactivate the extension. This feature aims to enhance the user experience by providing a more flexible approach to managing extensions

**Comment by CharlieS1103** [comment]
#12
