### ISSUE TITLE
Spicetify Marketplace never show up.

### ISSUE THREAD

**Issue by Rbom233** [spicetify/spicetify-marketplace#584]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version:1.12.18.999.g9b38fc27 (from my PC setting App management)
- Spicetify version: 2.22.2 (from powershell)
- Spicetify Marketplace version: 0.8.9
```

### 📝 Description

just marketplace do not show up. my net do not have any issues.

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-marketplace/assets/105418044/319e6dc5-40b7-46d2-8b54-e017b8e73f55)

**Comment by Rbom233** [comment]
like it always loading something, idk.

**Comment by CharlieS1103** [comment]
Update marketplace or try using a vpn if that doesn't work
