### ISSUE TITLE
This thing is solved can someone close this I dont know how

### ISSUE THREAD

**Issue by Fumi8481** [spicetify/spicetify-marketplace#585]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version:1.2.19.941.gbf202593
- Spicetify version:v2.22.2
```

### 📝 Description

My extensions don't work. And themes don't work. It says I have it all installed but it doesn't show. Only snippets work for me. 

### 📸 Screenshots

SPOTIFY GENRES:
![image](https://github.com/spicetify/spicetify-marketplace/assets/122705538/93241723-05ed-4469-b22c-53ded9dfd880)
![image](https://github.com/spicetify/spicetify-marketplace/assets/122705538/511043bf-e0fc-4052-8f34-0960893f4af3)
FULL SCREEN:
![image](https://github.com/spicetify/spicetify-marketplace/assets/122705538/44571566-5ec3-4050-b7ea-acafa906b967)
![image](https://github.com/spicetify/spicetify-marketplace/assets/122705538/c7790610-c5dd-4a2e-8168-95b599160f1b)
VOLUME PERCENTAGE:
![image](https://github.com/spicetify/spicetify-marketplace/assets/122705538/c71ba28d-a757-40ac-9d65-d10eec56f35b)
![image](https://github.com/spicetify/spicetify-marketplace/assets/122705538/266eebc5-471a-4f6b-b747-ace6315b9d2a)

**Comment by CharlieS1103** [comment]
Try updating marketplace, if that doesn't work ensure you don't have any firewalls or try using a vpn.

**Comment by Fumi8481** [comment]
> Try updating marketplace, if that doesn't work ensure you don't have any firewalls or try using a vpn.

THANK YOUUU!!!
