### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by olegkorol** [spicetify/spicetify-marketplace#593]
### 📝 Provide a description of the new feature

There are no instructions whatsoever on how to use `spicetify`. I've installed it and then what?

The docs do not help either:
> After installing Spicetify and Spicetify's Marketplace, you can use it to customize your Spotify client using all the available extensions and themes found in the Marketplace.

...use it how?

**Comment by rxri** [comment]
Issues are not for general inquiries. You mention the usage of spicetify however you're on marketplace repo. Docs are very clear what to do to use it in specific subpages

**Comment by olegkorol** [comment]
Alright. Got it.
I've figured it out, but I would strongly disagree with the docs being "very clear". The docs are not clear at all.
