### ISSUE TITLE
Marketplace "Something went wrong."

### ISSUE THREAD

**Issue by RottenCarrot21** [spicetify/spicetify-marketplace#595]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.72
- Spicetify version: 2.23.0
- OS: Linux
- The debian package i used: spotify-client_1.1.72.439.gc253025e_amd64.deb
```

### 📝 Description

I know about the other issues but i cant see my version so im posting.
to reproduce: press marketplace

**Comment by rxri** [comment]
Spicetify supports versions from 1.2.0 to 1.2.19. Your installed version (1.1.72) is not supported
