### ISSUE TITLE
Search bar collide with "Spicetify Marketplace" on small width

### ISSUE THREAD

**Issue by dhupee** [spicetify/spicetify-marketplace#596]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version:spotify 1:1.2.20.1210-1 AUR
- Spicetify version:spicetify-cli 2.23.2-1 AUR
```

### 📝 Description

The CSS doesn't take count of small width, and The search bar collides with the main title, at full size, It's working just fine, and it's not a breaking issue but worth taking a look at.

My suggestion is to fold the search bar when using a small width with the search icon.

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-marketplace/assets/32934122/3fb2d74f-77b3-421c-be28-7f3fc2b69ff6)

**Comment by SunsetTechuila** [comment]
lost its relevance after #545
