### ISSUE TITLE
Complete broken spotify on marketplace instalation, (using the prebuilt things with powershell)

### ISSUE THREAD

**Issue by Tr3yWay996** [spicetify/spicetify-marketplace#601]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: latest: 1.2.20.1218 (Thats the version i see in windows when i select spotify and look for properties)
- Spicetify version: latest: 2.32.2
idk if you meant my setup but i will still say it because idk

Ryzen 7 1700
32 GO 3000hz boosted ram
Radeon RX580
```

### 📝 Description

When installing the marketplace to get the extension that hide ads the screen aka spotify just wont load at all, idk if there is any kind of log somwere if yes just tell me, anyway so ye spotify become unusable when i install the marketplace with is basicaly why i wanna install spicetify in the first place fr

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-marketplace/assets/112483771/b1494d75-e39e-41f2-a435-697c59b2fd08)
![image](https://github.com/spicetify/spicetify-marketplace/assets/112483771/00cd22ba-8a57-441f-afc2-a62c6095060e)

**Comment by rxri** [comment]
Uninstall spotify, install it again and do `spicetify backup apply`. This'll resolve your issue

**Comment by Tr3yWay996** [comment]
> Uninstall spotify, install it again and do `spicetify backup apply`. This'll resolve your issue

okay i will try that thanks

**Comment by Tr3yWay996** [comment]
> Uninstall spotify, install it again and do `spicetify backup apply`. This'll resolve your issue

nah that aint working, still same result broken spotify again and i got this new message now, not updated for the new spotify update ? i talk about spicetify or watever the command you gave me install
![image](https://github.com/spicetify/spicetify-marketplace/assets/112483771/1929e659-c4ee-443f-85b9-b4ac923245a8)

**Comment by rxri** [comment]
Uninstall it again, delete everything related to spotify inside `%localappdata%` and `%appdata%`, then you can install spotify from the website. Spicetify is updated to work with 1.2.20 as mentioned in release notes.

**Comment by Tr3yWay996** [comment]
> Uninstall it again, delete everything related to spotify inside `%localappdata%` and `%appdata%`, then you can install spotify from the website. Spicetify is updated to work with 1.2.20 as mentioned in release notes

okay i wil ldo, if this dont work i will re open an issue with more information if i can because idk what to do, i'll go testing

**Comment by rxri** [comment]
Issues are not for general help. If you will still need one, please visit our discord server

**Comment by Tr3yWay996** [comment]
> Issues are not for general help. If you will still need one, please visit our discord server

oh okay i will surelly do, sorry to disturb you with this problem tho

**Comment by Tr3yWay996** [comment]
> Uninstall it again, delete everything related to spotify inside `%localappdata%` and `%appdata%`, then you can install spotify from the website. Spicetify is updated to work with 1.2.20 as mentioned in release notes

oh  and btw i use a script to uninstall spotify completly, and i dont find anything related to spotify in any of these two and this script i use it to fresh install and its still doing the issue sooo, hmm

**Comment by Tr3yWay996** [comment]
> Issues are not for general help. If you will still need one, please visit our discord server

man, nothing work still black screen and spicetify saying that version greater than 1.0.17 is not supported and that all fontions would not work as intended, for now i stop trying
![image](https://github.com/spicetify/spicetify-marketplace/assets/112483771/d86df7a7-f82b-403d-ba14-bdf2fb943910)

**Comment by DAIIIIIIIIIIIIII** [comment]
> Disinstallalo di nuovo, elimina tutto ciò che riguarda Spotify all'interno e , quindi puoi installare Spotify dal sito Web. Spicetify è aggiornato per funzionare con 1.2.20 come indicato nelle note di rilascio`%localappdata%``%appdata%`

I have the same problem, I did step by step, what you described, but nothing changes and spotify continues to be completely broken
