### ISSUE TITLE
Right sidebars close instantly upon opening

### ISSUE THREAD

**Issue by Tequinzyy** [spicetify/spicetify-marketplace#609]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.22.982.g794acc0a
- Spicetify version: v2.24.2
- Marketplace version: 0.9.0
```

### 📝 Description

All the right sidebars instantly close upon opening. I tried older Spotify version and the latest with Marketplace 0.8.9 as well, it behaved normally. Tried uninstalling all extensions and theme too. Vid attached

https://github.com/spicetify/spicetify-marketplace/assets/116754124/c5906d14-58ba-4347-b830-c62319e602b7

**Comment by rxri** [comment]
1.2.22 is not supported in latest release and is not listed as compatible in release notes

**Comment by rxri** [comment]
After testing, the necessary hooks work just fine. Try reinstalling (uninstalling and installing) Spotify, apply again and see if this issue still persists
