### ISSUE TITLE
My spotify is showing only black

### ISSUE THREAD

**Issue by riskaya** [spicetify/spicetify-marketplace#621]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version:I can't check on the spotify app but I uploaded the extension I used to install it
- Spicetify version:how
```

### 📝 Description

This started when my spicetify will remove itself everytime I open my spotify. I would reinstall the marketplace but it will only open to this

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-marketplace/assets/137668478/c8e33e2f-1479-47ce-a23e-97ef76482428)
![image](https://github.com/spicetify/spicetify-marketplace/assets/137668478/7fd2a103-3f63-414b-aecf-4ddd7a5b13ad)

**Comment by rxri** [comment]
Not cli or marketplace related. Follow faq on our discord server
