### ISSUE TITLE
Options to hide "By Spotify" playlists from search

### ISSUE THREAD

**Issue by Nerxxy** [spicetify/spicetify-marketplace#624]
### 📝 Provide a description of the new feature

(optional) Add an option in the settings that allows the user to hide playlists by spotify only in search.

Have a pill button next to the "all, audio books, playlists......" pills that allows a user to hide or show. This button would temporarily override the option in the settings 

### ➕ Additional Information

![image](https://github.com/spicetify/spicetify-marketplace/assets/37718547/c0d2ef2a-3bce-4775-b9d9-a5eda0710754)

![image](https://github.com/spicetify/spicetify-marketplace/assets/37718547/f5a010d0-373d-4d33-b845-c1c6a6ae0c98)

The option in settings would be the "main" option and the pill option is there to give qol to the user so they don't need to keep going into the settings to change the option as and when they wish.

The pill icon could also be the one and only since its state could get saved.

**Comment by SunsetTechuila** [comment]
what does this have to do with the marketplace?

**Comment by Nerxxy** [comment]
@SunsetTechuila uhhh on me mate i didnt realise i was on the marketplace, are you able to move it to the correct place? if not then i can just close and repost it myself

**Comment by Nerxxy** [comment]
moved it over.
