### ISSUE TITLE
failed to construct url: invalid url

### ISSUE THREAD

**Issue by ohitstom** [spicetify/spicetify-marketplace#632]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.22
- Spicetify version: 1.23.2
```

### 📝 Description

When trying to install the comfy theme on some systems this error is received, the css loads fine however the extension gets this error.

I dont believe this is an issue with how i've setup my manifest nor do i know how to troubleshoot this issue.

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-marketplace/assets/22730962/2ac800d6-23c6-43e6-8028-5e9433125881)

**Comment by ohitstom** [comment]
![image](https://github.com/spicetify/spicetify-marketplace/assets/22730962/be83b30f-0a56-4baa-ad93-9e3d543b8b25)

**Comment by ohitstom** [comment]
This happens on all branches except main for me, but for some users its all branches including main

**Comment by Delusoire** [comment]
Comfy/theme.script.js is not a url

**Comment by Delusoire** [comment]
Furthermore, it seems like the URL has to match this regex: `new RegExp("https:\\/\\/raw\\.githubusercontent\\.com\\/(?<user>[^/]+)\\/(?<repo>[^/]+)\\/(?<branch>[^/]+)\\/(?<filePath>.+$)")`

**Comment by Delusoire** [comment]
https://github.com/spicetify/spicetify-marketplace/blob/main/src/logic/Utils.ts#L477
isGithubRawUrl assumes that what's being passed is a URL.

**Comment by ohitstom** [comment]
> https://github.com/spicetify/spicetify-marketplace/blob/main/src/logic/Utils.ts#L477 isGithubRawUrl assumes that what's being passed is a URL.

i had assumed they would do the same thing they do with css files? i dont see why they wouldnt, i have swapped to raws. it doesnt help the docs state to NOT use raws and doesnt say that the include option is an exception.

**Comment by ohitstom** [comment]
this issue is still present after changing the urls.

**Comment by ohitstom** [comment]
the error stack doesnt point toward marketplace not sure why this error is happening
