### ISSUE TITLE
Now Playing Window instantly closes when clicked

### ISSUE THREAD

**Issue by Slipfar** [spicetify/spicetify-marketplace#634]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
Spotify for desktop-about.platform-win-x86-64
1.2.22.982.g794acc0a
Spicetify v2.25.1
Theme: Hazy / Base
Extensions: adblock.js, SleepTimer.js, volumePercentageWrapper.js, AnonymizedRadios.js, imageOpener.js, seekonscroll.js, imaged-folders.js, wikify.js, theme.js
Custom apps: marketplace, combined-playlists
```

### 📝 Description

Pressed the "Now Playing View" button, and instead of opening and showing the info, it opens and shows the info for about 0.1 seconds before instantly closing while still being "active" on the button.
Checked this on a mates computer, and we reinstalled spicetify twice, issue only occured when spicetify was installed.

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-marketplace/assets/70216977/a8aff424-6a2e-4d54-b299-f21a9fd7586a)

**Comment by rxri** [comment]
Not spicetify/marketplace related. Probably one of your extensions/custom apps does that

**Comment by SunsetTechuila** [comment]
or you messed up your backup and broke your xpui as a result
