### ISSUE TITLE
Unable to install marketplace through the command given in docs

### ISSUE THREAD

**Issue by sourabh412** [spicetify/spicetify-marketplace#648]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.22.982.g794acc0a
- Spicetify version: v2.25.3
- Location: India
```

### 📝 Description

the powershell command for downloading marketplace is not working
the uri: https://raw.githubusercontent.com/spicetify/spicetify-marketplace/main/resources/install.ps1 cannot be reached

### 📸 Screenshots

![image_2023-11-06_132639054](https://github.com/spicetify/spicetify-marketplace/assets/84635976/b316f91b-0764-4e33-8710-e393653a7fc1)

**Comment by rxri** [comment]
Try using VPN because it's something with the connection from you to GitHub
