### ISSUE TITLE
Hide now playing view button

### ISSUE THREAD

**Issue by GLWine** [spicetify/spicetify-marketplace#653]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version:(64 bit) 1.2.23.1125.g920a7ada
- Spicetify version:2.27.0
- SO: Windows 10 Pro 19045.3636
```

### 📝 Description

The Snippet called "Hide now Playing View Button" shows no signs of working once activated.
It doesn't actually hide the button that activates the "Now Playing View" section.
To be on the safe side, I tried closing Spotify and turning it back on again, but to no avail.
I assume he changed something that no longer makes this specific Snippet work

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-marketplace/assets/54741923/ea5bdea6-1cd2-4241-8a84-34a5e2b446c2)

**Comment by Diegomcha** [comment]
I added the following custom snippet with the "Add CSS" button and I successfully removed the button:
`button.Button-sc-1dqy6lx-0:has(span):has(svg):has(path[d='M11.196 8 6 5v6l5.196-3z']) { display: none; }`

I just took the original snippet and removed some class selectors that I guess changed in the new version. It's a messy solution but it works. Maybe someone finds it useful in the meantime :3
