### ISSUE TITLE
"more" dropdown doesnt display menu

### ISSUE THREAD

**Issue by ohitstom** [spicetify/spicetify-marketplace#654]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
Spotify for Windows (64 bit)
1.2.24.756.g7a7fc7f0
Spicetify v2.27.1
xpui_2023-11-06_1699279287548_7a7fc7f
cef_117.2.4+g5053a95+chromium-117.0.5938.150
```

### 📝 Description

The more button no longer drops down properly since root_topbar no longer exists in new versions of spotify

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-marketplace/assets/22730962/aab283e6-4788-4c2e-8a65-92c2774624f0)

**Comment by rxri** [comment]
Fixed by #655
