### ISSUE TITLE
Black Screen Error

### ISSUE THREAD

**Issue by ahmed18h** [spicetify/spicetify-marketplace#657]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version:1.2.24
- Spicetify version: last version (i just setup it throw the link)
```

### 📝 Description

Every Time I Write The Link In PowerShell Then I Try To Run After It Finishes And Gives Me That Every Thing Is Success When I Try To Open Spotify It Gives Me Blank 

### 📸 Screenshots

![czinjcoiaw](https://github.com/spicetify/spicetify-marketplace/assets/139806977/044c2745-dbec-406c-9212-de2171daacec)
![spoty](https://github.com/spicetify/spicetify-marketplace/assets/139806977/3847acfa-3fd5-46e0-b529-91d9813bebd9)

**Comment by SunsetTechuila** [comment]
![Screenshot](https://github.com/spicetify/spicetify-marketplace/assets/115353812/8f3c51c0-741d-44ef-89fd-b166e7f05cd1)

**Comment by SunsetTechuila** [comment]
It is not duplicate of 2672
He has outdated spicetify
