### ISSUE TITLE
Volume slider disabled

### ISSUE THREAD

**Issue by GalaxyVOID** [spicetify/spicetify-marketplace#660]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1:1.2.25.1011.g0348b2ea (Linux)
- Spicetify version:2.27.2
```

### 📝 Description

Install an extension or a theme.

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-marketplace/assets/94946192/b820cfd7-fc3f-4069-accb-9afbc8fbe561)

**Comment by rxri** [comment]
Not related to spicetify
