### ISSUE TITLE
Marketplace not showing as updated even after update

### ISSUE THREAD

**Issue by ImTrep** [spicetify/spicetify-marketplace#666]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.25.1011.g0348b2ea
- Spicetify version: 2.27.2
```

### 📝 Description

I downloaded the update files for marketplace 0.9.3 and after replacing them in %appdata%\roaming\spicetify\CustomApps\marketplace the application still asks to update in the marketplace tab

**Comment by theRealPadster** [comment]
You reapplied spicetify as well?

**Comment by ImTrep** [comment]
> You reapplied spicetify as well?
I was confusing the command spicetify backup apply with spicetify apply and i only realized it by looking at the automatic update .cmd that i made, i apologize for the inconvenience

**Comment by theRealPadster** [comment]
No worries. Could you close the issue if it's solved?
