### ISSUE TITLE
Stuck on "setting up..."

### ISSUE THREAD

**Issue by f-iturburu** [spicetify/spicetify-marketplace#676]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version:

Spotify for Windows (64 bits)
1.2.26.1187.g36b715a1

- Spicetify version: 2.28.1
```

### 📝 Description

Stucked on "setting up..." while installing Spicetify Marketplace

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-marketplace/assets/110144425/ed531961-faed-410b-86c7-5b9502e8a087)
![image](https://github.com/spicetify/spicetify-marketplace/assets/110144425/4c8d01de-8ac8-4a0f-b1f4-d344c19cdaa2)

**Comment by SunsetTechuila** [comment]
Run `spicetify path -s` and `spicetify path userdata`
Send the output

**Comment by f-iturburu** [comment]
![image](https://github.com/spicetify/spicetify-marketplace/assets/110144425/14b70069-d6b6-47b1-b994-52df47cd8a32)

Not getting anything on output

**Comment by SunsetTechuila** [comment]
now `spicetify config current_theme`

**Comment by f-iturburu** [comment]
> > No, I just stopped the proccess
> 
> You have to do this only after `spicetify config current_theme`? Or the same happens with other commands I send to you?

The same happened with all the other commands.

**Comment by SunsetTechuila** [comment]
Got it, thanks
If you have any questions - ask them on our discord support server

**Comment by SunsetTechuila** [comment]
I'll add some workaround for this

**Comment by rxri** [comment]
Not marketplace issue
