### ISSUE TITLE
Can't use Marketplace Themes on Mac

### ISSUE THREAD

**Issue by domi-btnr** [spicetify/spicetify-marketplace#677]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
Spotify for macOS (Apple Silicon)
1.2.26.1187.g36b715a1
Spicetify v2.29.1
xpui_2023-12-04_1701707306292_36b715a
cef_119.4.4+g5d1e039+chromium-119.0.6045.199
Runtime: Alloy
```

### 📝 Description

I recently reinstalled Spicetify and Spotify completely clean and tried to apply a Theme from the Marketplace. When I click Install in Marketplace, it tells me to set `current_theme` to `marketplace`. But when I do this, it tells me that the Theme doesn't exist and refuses to patch. I know that it says that my Spotify Version is too new, but that shouldn't affect the check for the Theme

### 📸 Screenshots

Terminal Error:
<img width="619" alt="image" src="https://github.com/spicetify/spicetify-marketplace/assets/50876016/2ed0b0fb-cd7f-4344-b8b0-1755c9dd03e9">

Marketplace Error:
<img width="711" alt="image" src="https://github.com/spicetify/spicetify-marketplace/assets/50876016/7074ee7b-a52f-4769-8a68-86abf4108db5">

**Comment by SunsetTechuila** [comment]
Run the marketplace installation script 
If you have any difficulties with that - use our discord server to get support
