### ISSUE TITLE
Marketplace Devtools Errors.

### ISSUE THREAD

**Issue by TheDarkKnight69** [spicetify/spicetify-marketplace#687]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for Windows 1.2.5.1006.g22820f93
- Spicetify version: 2.14.2
```

### 📝 Description

I installed the newest version of marketplace as well as 0.9.0. But it gives me the error "Unexpected error occured please try again". 
On opening the console log, I see this
![image](https://github.com/spicetify/spicetify-marketplace/assets/91176991/9ca4b193-5e91-4c63-9480-0acb385d059b)

**Comment by CharlieS1103** [comment]
not a marketplace error, put this in the cli repo
