### ISSUE TITLE
use zero cache system for extensions - esm

### ISSUE THREAD

**Issue by ohitstom** [spicetify/spicetify-marketplace#697]
### 📝 Provide a description of the new feature

i recommend using esm over jsdelivr https://esm.sh

### ➕ Additional Information

no more 8 hour wait for extensions to update

**Comment by rxri** [comment]
v3 will not load extensions/custom apps or whatever via cdn anyway. I think `esm.sh` is blocked in some countries as well that's why we use jsdelivr since they have many domains

**Comment by ohitstom** [comment]
> v3 will not load extensions/custom apps or whatever via cdn anyway. I think `esm.sh` is blocked in some countries as well that's why we use jsdelivr since they have many domains

i see, how will we get around this may i ask that sounds cool

**Comment by rxri** [comment]
wdym. Marketplace will just be a "middleman" between the user and cli. CLI will download everything

**Comment by ohitstom** [comment]
> wdym. Marketplace will just be a "middleman" between the user and cli. CLI will download everything

how will things be kept up to date?
