### ISSUE TITLE
Apps Doesn't Show On UI

### ISSUE THREAD

**Issue by Error-Cezar** [spicetify/spicetify-marketplace#708]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.13
- Spicetify version: 2.36.0
```

### 📝 Description

I have installed Spicetify on my spotify under 1.2.13 (with ver 2) 
It registers Marketplace & Lyrics plus as installed on my spotify, but the following doesn't show for unknown reasons
I have tried to modify the sidebar configuration with no success

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-marketplace/assets/64325581/059ea2d7-670d-4272-8d83-6cf5650b210d)
![image](https://github.com/spicetify/spicetify-marketplace/assets/64325581/0f63b82c-e6e6-4ca2-86b6-b77e5753246f)

**Comment by rxri** [comment]
Not related to marketplace and they do show up
![image](https://github.com/spicetify/spicetify-marketplace/assets/9348108/5c65d87d-5dc2-442f-bd02-b596e1bc1e0a)

**Comment by Error-Cezar** [comment]
![image](https://github.com/spicetify/spicetify-marketplace/assets/64325581/c5669465-dc09-4c1a-810a-810fe2fa0028)

**Comment by rxri** [comment]
We do not support pre-Library X UI anymore. If you need it, downgrade to spicetify version that did not support global navbar
