### ISSUE TITLE
Can't install extensions & themes from the marketplace

### ISSUE THREAD

**Issue by Amiru2007** [spicetify/spicetify-marketplace#711]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.33.1042.g26c92729
- Spicetify version: v2.36.0
```

### 📝 Description

After updating both the Spotify client and Spicetify. I have encountered a new issue in that I am unable to install extensions or themes. I have encountered this problem several times in the past as I have installed a large number of extensions, and I have removed some of them and installed new extensions on my own. In addition, this time I was unable to install either extensions or themes after uninstalling several extensions.

**Comment by rxri** [comment]
If nothing works, then jsdelivr domains are blocked for you and we cannot do anything about it. Install extensions manually

**Comment by Amiru2007** [comment]
Is there a way to resolve the problem on my side, I am hesitating to uninstall Marketplace and install it again as I've some previously installed extensions such as AdBlock from the current Marketplace and if the newly installed Marketplace still had the issue I would lose them too.
