### ISSUE TITLE
Marketplace not displaying

### ISSUE THREAD

**Issue by iamnovichek** [spicetify/spicetify-marketplace#713]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.31.1205.g4d59ad7c
- Spicetify version: 2.36.1
- OS: Linux Mint 21.2
```

### 📝 Description

Hi! I just installed spacetify using
```
curl -fsSL https://raw.githubusercontent.com/spicetify/spicetify-cli/master/install.sh | sh
```
Than I ran this command to create my backups 
```
spicetify backup apply enable-devtools
```
Finally I restarted my PC and opened Spotify.

### 📸 Screenshots

![spotify](https://github.com/spicetify/spicetify-marketplace/assets/60839899/eccff550-3bf3-4eb4-b918-888eb5eb342b)

**Comment by rxri** [comment]
```
spicetify config custom_apps marketplace
spicetify config current_theme marketplace
spicetify apply
```

**Comment by iamnovichek** [comment]
@rxri I ran the commans set you provided and got Permission denied error 
```
spicetify config custom_apps marketplace
spicetify config current_theme marketplace
spicetify apply
warning Config "custom_apps" unchanged: marketplace is already in the list.
success Config changed: current_theme = marketplace
info Run "spicetify apply" to apply new config
spicetify v2.36.1
info Spicetify up-to-date
Copying raw assets:
fatal unlinkat /var/lib/flatpak/app/com.spotify.Client/x86_64/stable/active/files/extra/share/spotify/Apps/xpui.spa: permission denied
```
So I reran it one more time but with sudo and got this problem
```
sudo spicetify config custom_apps marketplace
sudo spicetify config current_theme marketplace
sudo spicetify apply

sudo: spicetify: command not found
sudo: spicetify: command not found
sudo: spicetify: command not found
```
Actually I guess I didn't configure correctly spicetify and that's why I get all these problems. Isn't it?

**Comment by rxri** [comment]
https://spicetify.app/docs/advanced-usage/installation#spotify-installed-from-flatpak
![image](https://github.com/spicetify/spicetify-marketplace/assets/9348108/b17ac4d6-0a15-42a7-8933-6a49d6bb240f)

**Comment by iamnovichek** [comment]
@rxri I ran the commans set you provided and got Permission denied error 
```
spicetify config custom_apps marketplace
spicetify config current_theme marketplace
spicetify apply
warning Config "custom_apps" unchanged: marketplace is already in the list.
success Config changed: current_theme = marketplace
info Run "spicetify apply" to apply new config
spicetify v2.36.1
info Spicetify up-to-date
Copying raw assets:
fatal unlinkat /var/lib/flatpak/app/com.spotify.Client/x86_64/stable/active/files/extra/share/spotify/Apps/xpui.spa: permission denied
```
So I reran it one more time but with sudo and got this problem
```
sudo spicetify config custom_apps marketplace
sudo spicetify config current_theme marketplace
sudo spicetify apply

sudo: spicetify: command not found
sudo: spicetify: command not found
sudo: spicetify: command not found
```
Actually I guess I didn't configure correctly spicetify and that's why I get all these problems. Isn't it?

**Comment by iamnovichek** [comment]
@rxri Love you!!!!!
