### ISSUE TITLE
Can't change theme

### ISSUE THREAD

**Issue by SeiRann** [spicetify/spicetify-marketplace#723]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version:1.2.33.1042.g26c92729
- Spicetify version:2.36.2
```

### 📝 Description

I'm having an issue where UI is little bugged and the categories are overlapped and also I can't search for themes/extensions/etc. the search bar doesn't work in general and the little theme selector also doesn't work,
image

I have changed themes, thought maybe it was because of the theme but it isn't. I reinstalled spotify and reapplied spicetify nothing changed. A little bit of help if anyone already had this issue would be appreciated. 🙏

### 📸 Screenshots

And the UI is a little bugged here.
![image](https://github.com/spicetify/spicetify-marketplace/assets/70053735/1cdff968-b9cc-449b-b4ca-d851d2e04e0f)
These 2 don't work
![image](https://github.com/spicetify/spicetify-marketplace/assets/70053735/6795a356-f158-4cbf-9bd5-c9acc0f36472)

**Comment by theRealPadster** [comment]
Check if you have any extensions installed/enabled in your config file. Could be an extension for a theme that you forgot to remove.

**Comment by SeiRann** [comment]
Where is the config file?

**Comment by theRealPadster** [comment]
Depends on your OS. If you run `spicetify config-dir`, it should open the folder up. It's the `config-xpui.ini` file inside there.

**Comment by rxri** [comment]
These work just fine. TabBar is overlapping because of spotify changes that we won't really re-implement in v2.
