### ISSUE TITLE
Marketplace settings tab not applying

### ISSUE THREAD

**Issue by b-chen00** [spicetify/spicetify-marketplace#724]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.34.783.g923721d9 Windows (64 bit)
- Spicetify version: 2.36.2
```

### 📝 Description

Turning off tabs in the marketplace settings doesn't affect shown tabs and isn't applied. I have tried updating and uninstall/reinstalling both Spicetify and Spotify. I don't have any extensions and the theme is the marketplace placeholder.

### 📸 Screenshots

![spicetifytab](https://github.com/spicetify/spicetify-marketplace/assets/90290521/d28797e9-e81a-45f0-8f44-4727d2320b32)

**Comment by Sorata0** [comment]
Can confirm. Personally I'm stuck in the installed tab, and reloading reverts any change applied to this tabs window

**Comment by Miguel22247** [comment]
Hi, I came across this bug also on MacOS and I installed it again with the command provided [here](https://github.com/spicetify/spicetify-marketplace/wiki/Installation) and I now have again the tabs back, i will try later on my Windows PC to verify if this steps that i did could work as a workaround

**Comment by b-chen00** [comment]
I tried the Powershell command provided for Windows without much luck. I will see if the manual installation will fix the issue. Other than that, for a bit more information, I do see the unchecked tab disappearing when I click out of the settings but the subsequent reload brings it back.

**Comment by grejprrik** [comment]
> I installed it again with the command provided [here](https://github.com/spicetify/spicetify-marketplace/wiki/Installation)

YES! This method works. Installed it again and I have it all back!

![image](https://github.com/spicetify/spicetify-marketplace/assets/160502398/9eaf8f48-d419-447c-9909-dd838062f66a)

**Comment by CharlieS1103** [comment]
Update marketplace if you encounter this issue.

**Comment by MasklessFate** [comment]
It still doesnt work even after manually installing it or using the powershell command

**Comment by Vladimer17** [comment]
> Hi, I came across this bug also on MacOS and I installed it again with the command provided [here](https://github.com/spicetify/spicetify-marketplace/wiki/Installation) and I now have again the tabs back, i will try later on my Windows PC to verify if this steps that i did could work as a workaround
> 
> Update: I did the same steps on Windows and i have the tabs back as well

I had the same issue and reinstalling with the powershell command in the link brought it back

**Comment by AmRam841** [comment]
![Screenshot_2024-12-31_13_36_54](https://github.com/user-attachments/assets/16c44bcc-0a19-4122-8439-adaf33cfc541)

im facing a wierd issue , i have installed spicetify using the recommended way , i had some problems with the key (where the key that was in the command was differnt to the one kali requsted so i fixed it by placing the same command diffrent numbers) 
i had another problem with the perfs so i had to manully set the path in the spicetify config-dir (using the spicetify config-dir) , i looked for a perf file in the spotify path i did not find it bc there was only onw path , so i copied the same path as spotify_path , it worked no errs or anything like that but i when i open the spotify app i dont see ant marketplace  soooo i ran out of ideas a lil help would be nice thanks in advance

**Comment by AmRam841** [comment]
`curl -fsSL https://raw.githubusercontent.com/spicetify/spicetify-marketplace/main/resources/install.sh | sh
FETCHING Version 1.0.2
DOWNLOADING https://github.com/spicetify/marketplace/releases/download/v1.0.2/marketplace.zip
######################################################################## 100.0%
EXTRACTING
COPYING
INSTALLING
warning Config "custom_apps" unchanged: spicetify-marketplace is not on the list.
success Config changed: inject_css = 1
info Run "spicetify apply" to apply new config
success Config changed: replace_colors = 1
info Run "spicetify apply" to apply new config
warning Config "custom_apps" unchanged: marketplace is already in the list.
Added to config!
APPLYING
spicetify v2.38.7
info Spicetify up-to-date
BOM: read /usr/share/spotify/: is a directory
                                                   `
this is what it says when i run the recommended command  , everything seems okay but still nothing in the app , i tried spicetify back up command as well nothing worked

**Comment by AmRam841** [comment]
okayy , after some reading i just reinstalled the spicetify and it worked like magic , everything was automaticly set coerectly and Boom!! it worked
