### ISSUE TITLE
No more categories in the Marketplace

### ISSUE THREAD

**Issue by Nans-ssss** [spicetify/spicetify-marketplace#726]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.34.783.g923721d9
- Spicetify version: 2.36.2
```

### 📝 Description

There are no more categories in the Marketplace

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-marketplace/assets/146657048/a2cd09f6-c9e3-4978-b0d5-a0ae12b1f45a)

**Comment by rxri** [comment]
Update marketplace
