### ISSUE TITLE
Marketplace is broken

### ISSUE THREAD

**Issue by notyormom** [spicetify/spicetify-marketplace#728]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version:   1.2.34.783.g923721d9
- Spicetify version: v2.36.2
```

### 📝 Description

when i go to the marketplace and want to look for themes, or extensions, i can't because i can only search for ,,snippets'' idk why or if its just my theme, that bugs and i cannot solve the problem because i can't get to the ,,installed tab''.

### 📸 Screenshots

![Screenshot (358)](https://github.com/spicetify/spicetify-marketplace/assets/166249572/357e8684-d158-4a96-b667-ec07060c7676)

**Comment by rxri** [comment]
Update marketplace (run marketplace install script)

**Comment by sTiKyt** [comment]
> Update marketplace (run marketplace install script)

It doesn't help
