### ISSUE TITLE
Maketplace button disappearing on app start

### ISSUE THREAD

**Issue by Botond24** [spicetify/spicetify-marketplace#730]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1:1.2.8.923.g4f94bf0d
- Spicetify version: 2.36.3
- OS: Linux Mint 21.3 Cinnamon
```

### 📝 Description

1. Install Spotify from Software Manager (apt)
2. Run the app and log in
3. Install Spicetify & Marketplace
4. Open Spotify

Similar to #439 
Tried the given fix there, but the marketplace button disappears again after a restart of the app.

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-marketplace/assets/44529287/67e8c4b3-e854-430e-b782-fa9619ac8175)

**Comment by rxri** [comment]
Spotify 1.2.8 is not a supported version by spicetify version listed in your issue description

**Comment by Botond24** [comment]
Thank you for the info, my repository.spotify.com publickey was missing.
Managed to update to 1:1.2.31.1205.g4d59ad7c

**Comment by Botond24** [comment]
But it looks like it still needs LibraryX disabled to appear at all

Is that inteded?

**Comment by rxri** [comment]
You probably did hide it via Sidebar config. LibraryX is supported.
