### ISSUE TITLE
Marketplace not functioning correctly

### ISSUE THREAD

**Issue by charklie** [spicetify/spicetify-marketplace#743]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.31.1205.g3d59ad7c (spotify-launcher)
- Spicetify version: v2.36.10 (from aur)
- Kernel version: 6.8.9-arch1-1

On EndeavourOS with Hyprland (Wayland)
```

### 📝 Description

When I put `marketplace` in current_theme, it gives me this error: 
```
error Theme "marketplace" not found
```

this is my config-xpui.ini:
```ini
[Patch]

[Setting]
overwrite_assets       = 0
always_enable_devtools = 0
spotify_path           = $HOME/.local/share/spotify-launcher/install/usr/share/spotify/
prefs_path             = /home/charlie/.config/spotify/prefs
current_theme          = marketplace
color_scheme           = 
inject_theme_js        = 1
inject_css             = 1
replace_colors         = 1
spotify_launch_flags   = 
check_spicetify_update = 1

[Preprocesses]
disable_sentry     = 1
disable_ui_logging = 1
remove_rtl_rule    = 1
expose_apis        = 1

[AdditionalOptions]
extensions            = 
custom_apps           = marketplace
sidebar_config        = 1
home_config           = 1
experimental_features = 1

; DO NOT CHANGE!
[Backup]
version = 1.2.31.1205.g4d59ad7c
with    = 2.36.10
```

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-marketplace/assets/157241212/c72515b8-9969-4299-ad00-1aab18205b5b)

**Comment by charklie** [comment]
Extensions, snippets and apps work fine though

**Comment by rxri** [comment]
If `marketplace` theme cannot be found. Run install script (https://github.com/spicetify/spicetify-marketplace/wiki/Installation) and it will work

**Comment by Kazuto** [comment]
Does not work for me unfortunately.

![Image](https://github.com/user-attachments/assets/bf158885-0e57-4cce-82d3-9d5479222be5)

**Comment by rxri** [comment]
> @rxri this happens on the latest version of spicetify, even after running the install script.

Then set it manually and if marketplace theme is missing then create a folder manually and color.ini file
