### ISSUE TITLE
Not able to browse for extensions on new spotify update

### ISSUE THREAD

**Issue by kylewhirl** [spicetify/spicetify-marketplace#747]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version:
1.2.37.701
- Spicetify version:
2.36.11
```

### 📝 Description

Unsure why but Spicetfiy Marketplace only shows installed extensions. Not able to browse or add extensions

**Comment by rxri** [comment]
Not cli related. Update marketplace by installing it again

**Comment by sTiKyt** [comment]
Same here, tried reinstalling, nothing helps

![image](https://github.com/spicetify/marketplace/assets/35602029/3e1a5c13-64ea-4b2e-bc76-3eeb25e8f274)
