### ISSUE TITLE
Addon by url

### ISSUE THREAD

**Issue by ohitstom** [spicetify/spicetify-marketplace#77]
**Is your feature request related to a problem? Please describe.**
Some Creators Not Using A Manifest (or outdated content)

**Describe the solution you'd like**
A clickable box at the end of lists of extensions/themes/whatever with a plus icon with the text (import url) or some shit along those lines, or just a dropdown option somwhere. You can then input an url and specify anything that you might need to such as usercss, schemes, includes etc.

**Describe alternatives you've considered**
"HEY YOU KNOW ON MARKETPLACE YOU CAN ADD YOUR THEMES HUH, EVER HEARD OF MARKETPLACE???????!?!?!?!?!?!?!??!?!!??!?!?!?!?!?!?!?!?!?!?!?!?!?!?!?!?!?!?!????????????"

**Comment by theRealPadster** [comment]
Going to close this because we will be moving over to a mono-manifest approach where you can just make a PR to the main repo and add whatever theme you want to it.
