### ISSUE TITLE
Better validate authors manifest values

### ISSUE THREAD

**Issue by theRealPadster** [spicetify/spicetify-marketplace#86]
Since the authors and URLs are being directly used in the react code, we might want to parse or something to make sure people don't put JavaScript in the url field that runs on click or something. It also might be worth looking into how other values are used and parsed.

**Comment by CharlieS1103** [comment]
@theRealPadster Is this still relevant?

**Comment by theRealPadster** [comment]
I thought so, since you could theoretically do something like this. 
<img width="979" alt="image" src="https://user-images.githubusercontent.com/1565883/170843730-f8f12fa7-acba-49a3-a92b-75f3848292e1.png">
But it doesn't look like it runs when I do click it. Because of the `onClick={(e) => e.stopPropagation()}` maybe? 
<img width="401" alt="image" src="https://user-images.githubusercontent.com/1565883/170843764-beebe046-c917-45a9-ae90-ee336ce4ed33.png">
