### ISSUE TITLE
Snippest are wrong size in installed tab

### ISSUE THREAD

**Issue by CharlieS1103** [spicetify/spicetify-marketplace#87]
We should either A: Create a different way to install and uninstall snippets (maybe a checkbox list but meh) B: Put all the snippets before or after everything in installed tab

**Comment by theRealPadster** [comment]
The cards are all the same height, so if the row has extensions in them, it will stretch them out. We'd have to put them in separate wrappers/rows if we wanted to have it not do that.

**Comment by theRealPadster** [comment]
This would likely require a check in the main Grid `render` function, that renders the headings if it's the "installed" tab. Or have a separate `cardList` for each type, and render headings if there is more than one type present. I think the first option makes more sense.
